### ISSUE TITLE
Robo 2.2.2: PHP Fatal error

### ISSUE THREAD

**Issue by borgogelli** [consolidation/robo#1016]
- Robo: 2.2.2 phar package (!)
- OS: Windows
- PHP: 7.2.9

Command:
`robo -V`

Returns:
```
PHP Fatal error:  Class Robo\Tasks contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Consolidation\AnnotatedCommand\State\SavableState::currentState) in C:\Users\Borgo\workspace-php\php-iubar-builder\vendor\consolidation\robo\src\Tasks.php on line 11

Fatal error: Class Robo\Tasks contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Consolidation\AnnotatedCommand\State\SavableState::currentState) in C:\Users\Borgo\workspace-php\php-iubar-builder\vendor\consolidation\robo\src\Tasks.php on line 11
```

**Comment by greg-1-anderson** [comment]
I cannot reproduce on PHP 7.3.  Where are you getting your robo.phar? I don't see a .phar on the 2.2.2 release on GitHub, and robo.li points at the 2.2.1 robo.phar. Does this one also fail for you?

**Comment by greg-1-anderson** [comment]
`currentState` is defined in the IO trait. If this construct is somehow not legal in older versions of PHP, then I'm not sure why the tests would be passing.

Please see if you can provide further isolation of the problem you are experiencing.

**Comment by borgogelli** [comment]
I'm very very sorry Greg, my eyes crossed, I have downloaded the 2.1.0 thinking it was the 2.2.2. 
The 2,2,1 is ok for me

**Comment by borgogelli** [comment]
Please delete the issue

**Comment by dashifen** [comment]
Actually, this is happening to me, too.  I executed `composer require consolidation/robo` and it loaded version 2.2.2 according to my `composer.lock`.  I then tried to do the [`Hello, $world` example](https://robo.li/getting-started/) from the docs, but I get the same error.  

As with the prior posts, even `robo -V` produces this error.  In fact, any use of robo produces this error, even arguments that have no definition (e.g. `robo --asdfasdfasdfasdf`).

I downgraded to 2.2.1 as was mentioned above, and the error continues.  I can see where the `currentState` function is defined in the IO trait, but the error continues.

OS is Win10, PHP version is 7.4.14.

**Comment by greg-1-anderson** [comment]
@dashifen Try `composer update` and see if that helps. Just do `consolidation/*` if you don't want to do everything. If that doesn't work, include the output of `composer info consolidation/*`

**Comment by dashifen** [comment]
`composer update` didn't do anything, though that's likely because I had specified that `consolidation/robo` must be at version `2.2.1` based on the above conversation.  If I switch it back to `^2.2` as it was by default, then it upgrades back to `2.2.2` as one would expect.  

I'm not sure what you wanted me to do with `consolidation/*`, but the following is the output of the composer info for it:

```
consolidation/annotated-command 4.2.4 Initialize Symfony Console commands from annotated command class methods.
consolidation/config            2.0.1 Provide configuration services for a commandline tool.
consolidation/log               2.0.2 Improved Psr-3 / Psr\Log logger based on Symfony Console components.
consolidation/output-formatters 4.1.2 Format text by applying transformations provided by plug-in formatters.
consolidation/robo              2.2.2 Modern task runner
consolidation/self-update       1.2.0 Provides a self:update command for Symfony Console applications.
```

**Comment by greg-1-anderson** [comment]
@dashifen OK looks like your dependencies are all up to date. I could not reproduce this problem and the tests are passing, so I'm going to need more info on why this is happening for you.

**Comment by dashifen** [comment]
Well, this is everything I've done so far:  https://github.com/dashifen/photo-backup

The goal was to investigate Robo as a framework to replace a series of scripts that were originally written using the Cilex framework that has been abandoned.  To start out, I was going to take a script currently using [AutoHotKey](https://www.autohotkey.com/) and port it into PHP using Robo.

But, even just entering `robo` on the command line results in the above error.

**Comment by greg-1-anderson** [comment]
I cloned your repo, ran `composer install`, and then:

```
$ ./vendor/bin/robo hello there
➜  Hello, there
```

**Comment by dashifen** [comment]
Ah!  The docs didn't say anything about having to specify a path to the robo file.  If I do that, it's fine.  I thought I had to download the .phar file (as discussed above) but when the `robo` command was "known" to the command line, I thought something else was going on.

Thanks!

**Comment by greg-1-anderson** [comment]
Might be a bug with phar packaging, or you might have a different robo.phar on your $PATH than you expected.

**Comment by greg-1-anderson** [comment]
I tried with the .phar and was successful with that as well:
```
$ ~/Code/open-source/consolidation/robo/robo.phar hello there
➜  Hello, there
```
Maybe you had an old Robo in your $PATH or something like that.
