### ISSUE TITLE
"Interface 'Consolidation\AnnotatedCommand\Output\OutputAwareInterface' not found" with Robo 3

### ISSUE THREAD

**Issue by kolaente** [consolidation/robo#1021]
### Steps to reproduce

1. Upgraded my laravel project with an existing Robofile to use the newest robo 3.
2. Ran a command from the Robofile 

### Expected behavior

Command works without issues.

### Actual behavior

Instead, I get this error message: 

```
$ ./vendor/bin/robo setup

Fatal error: Uncaught Error: Interface 'Consolidation\AnnotatedCommand\Output\OutputAwareInterface' not found in ./vendor/consolidation/robo/src/Contract/OutputAwareInterface.php on line 14

Error: Interface 'Consolidation\AnnotatedCommand\Output\OutputAwareInterface' not found in ./vendor/consolidation/robo/src/Contract/OutputAwareInterface.php on line 14
```

It doesn't seem to matter what I put in the Robofile, the error happens even if I remove all commands.

I tried to reproduce this with an empty new repo, but it worked without issues. I then dug a little deeper and found out the missing interface is located in the package `consolidation/annotated-command`. Even though it is required and installed in both cases, my existing project seems to use version 4.1.1 whereas the new reproduce test project seems to use 4.2.4. It looks like the dependencies got somehow messed up?
This could mean the issue is not with robo but somewhere else.

### System Configuration

Nixos 20.09 locally, also happens in a docker `7.4-apache` docker container.

**Comment by kolaente** [comment]
After just upgrading all dependencies (don't worry, they're all pinned in my `composer.json`) with 

```
composer upgrade --with-all-dependencies
```

it seems to work again.

Looks like renovate messed something up here.

**Comment by kolaente** [comment]
So clearly not an issue with robo, so I'm closing this issue.

**Comment by kolaente** [comment]
I'm not sure why it worked the last time, it didn't a second time. Figured I'd open an issue at composer with more detail this time: https://github.com/composer/composer/issues/9723

**Comment by greg-1-anderson** [comment]
I don't think this is a Consolidation or Composer bug; perhaps something in your lock file. I commented on the Composer issue.

**Comment by greg-1-anderson** [comment]
Fixed in Packagist. See comments on Composer issue.
