### ISSUE TITLE
escapeArgument deprecation error

### ISSUE THREAD

**Issue by JKingweb** [consolidation/robo#1023]
### Steps to reproduce
`$this->taskExec("php")->option("-d", "zend.assertions=1")->arg("example.php")->run();`

### Expected behavior
Robo should run the task without issue

### Actual behavior
Robo runs the task and then prints this message:

> ERROR: The Robo\Common\ProcessUtils::escapeArgument() method is a copy of a method that was deprecated by Symfony 3.3 and removed in Symfony 4; it will be removed in Robo 2.0. 
in ./vendor/consolidation/robo/src/Common/ProcessUtils.php:39

This is despite running Robo 3.0. :P Using `->option()` is the source of the problem; I including an argument for clarity because one must otherwise quit PHP with Ctrl+D to make the error appear.

### System Configuration
Which O.S. and PHP version are you using?

PHP 8.0.2, Linux

**Comment by greg-1-anderson** [comment]
Looks like that deprecated method is overdue for being removed. Run without `E_USER_DEPRECATED` to avoid seeing deprecated warnings.

PRs to clean up taskExec welcome.

**Comment by markdorison** [comment]
I see a PR was created for this against 3.x which is fantastic. What should the approach to 2.x be? Should this be backported if committed or should the error message be updated to note that it will be removed in 3.x (instead of 2.0)?

**Comment by greg-1-anderson** [comment]
If that PR does land on the 3.x branch, it could probably be backported to 2.x.  If it ends up with bc breaks, then it will have to be 4.x, in which case there might be the possibility of making a simpler version for 2.x and 3.x.

**Comment by greg-1-anderson** [comment]
Oh, I was thinking of https://github.com/consolidation/Robo/pull/1038, not https://github.com/consolidation/Robo/pull/1036.

**Comment by greg-1-anderson** [comment]
#1038 does not address the problem with escape in a way that solves this issue. Maybe the best solution is to simply un-deprecate this method in 2.x and 3.x (replace the trigger_error with a comment), and re-deprecate it once there is an actual replacement for escapeArgument. I think I was wrong in my Feb comment; this deprecation was premature; it therefore could be removed as a bugfix.

**Comment by greg-1-anderson** [comment]
Also, for all who visit here, I will also mention that it is also advisable to just use Symfony Process directly if you want to exec a process and get some result that you use to build your task list. TaskExec is good for adding operations in the middle of a task list where you do not need to capture the result, or as the last operation in a task list.
