### ISSUE TITLE
PHPStan: Call to an undefined method Robo\Collection\CollectionBuilder::taskFilesystemStack().

### ISSUE THREAD

**Issue by markdorison** [consolidation/robo#1059]
### Steps to reproduce
1. Mimic usage of `CollectionBuilder::taskFilesystemStack()` shown in `CollectionBuilder` docblock: https://github.com/consolidation/robo/blob/2327540baf5ada22687725f21177cd4affb878ff/src/Collection/CollectionBuilder.php#L32-L35
Actual code:
```php
return $this->collectionBuilder()
            ->taskFilesystemStack()
            ->remove($path1)
            ->remove($path2)
            ->run();
```
2. Configure [PHPStan](https://github.com/phpstan/phpstan) to run at a minimum of level 2.
3. Run `phpstan analyze`

### Expected behavior
No error.

### Actual behavior
PHPStan reports: `Call to an undefined method Robo\Collection\CollectionBuilder::taskFilesystemStack().`

PHPStan seems to be trying to find the `taskFilesystemStack()` method in [`CollectionBuilder`](https://github.com/consolidation/robo/blob/3.x/src/Collection/CollectionBuilder.php) but is unable to trace it back. I see that it is actually located in the [`Tasks` trait](https://github.com/consolidation/robo/blob/3.x/src/Task/Filesystem/Tasks.php#L79-L86). **Should I tell PHPStan to ignore this or is there something that can/should be done here in Robo to allow PHPStan to understand what is going on?**

Side note: this also occurs for `CollectionBuilder::taskReplaceInFile()`: `Call to an undefined method Robo\Collection\CollectionBuilder::taskReplaceInFile().` Whatever the issue is I am assuming it is the same cause.

### System Configuration
MacOS 12.0.1
PHP 8.0.12

**Comment by greg-1-anderson** [comment]
Robo magic task collection methods are not compatible with static analysis tools.

Rewrites welcome.

**Comment by markdorison** [comment]
Understood. Thanks!

**Comment by prudloff-insite** [comment]
In cas anyone else wonders, it is possible to use phpstan with Robo. You can use this pattern:
```php
    $execTask = $this->taskExec('cmd');
    assert($execTask instanceof Exec);
    $execTask->arg('arg');
```
