### ISSUE TITLE
Exec eats a lot of CPU while waiting

### ISSUE THREAD

**Issue by Rarst** [consolidation/Robo#109]
I have noticed that if I launch long running programs with Exec (for example BrowserSync) then Robo starts to consume a lot of CPU just sitting there and waiting. It's about 12% in my system (Core i7 CPU, Win7x64).

It's clearly on PHP side as shown by Process Explorer and it's not the issue if I run exactly same command directly in console.

**Comment by burzum** [comment]
Can you please run the same command through exec() inside a normal php file and simply do `php testfile.php` to see if the issue is specific to exec() or something inside Robo?

**Comment by Rarst** [comment]
Sorry, lost track of this. :) Just running it with exec doesn't stress CPU, might be something outtput-related? Exec is not sending realtime output to console, right?

Call in Robo:

```php
public function sync( $slides ) {
	$this->taskExec( 'browser-sync start' )
	     ->arg( '--host "dev.rarst.net" --open external' )
	     ->arg( '--files "shared.css,' . $slides . '/index.html"' )
	     ->arg( '--proxy "dev.rarst.net/slides/' . $slides . '"' )
	     ->run();
}
```

Call in plain PHP

```php
exec('browser-sync start --host "dev.rarst.net" --open external --files "shared.css,answering/index.html" --proxy "dev.rarst.net/slides/answering"');
```

**Comment by Rarst** [comment]
Anything else I can do to help figure this out? :)

**Comment by greg-1-anderson** [comment]
Closed due to lack of activity.

I will add that taskExec just calls through to the Symfony Process component. This issue would probably be best addressed there, if it is still a problem.
