### ISSUE TITLE
Implicit conversion from float to int loses precision

### ISSUE THREAD

**Issue by Sweetchuck** [consolidation/robo#1094]
### Steps to reproduce
Need a task which runs 5-10 minutes.
The error message **can't** be reproducible all the time.

### Expected behavior
To see the duration time at the end of the output.

### Actual behavior
> ERROR: Implicit conversion from float 105.24845504760742 to int loses precision 
in /.../vendor/consolidation/robo/src/Common/TimeKeeper.php:72

### System Configuration

I have seen this error message in different docker containers (openSUSE Tumbleweed, Fedora 36, Ubuntu 21.10)
PHP 8.0, 8.1

php -i | grep prec
> precision => 14 => 14
> serialize_precision => -1 => -1

Maybe this one is related: https://php.watch/versions/8.1/deprecate-implicit-conversion-incompatible-float-string

**Comment by Sweetchuck** [comment]
Related to #1071

**Comment by Sweetchuck** [comment]
I started to work on the fix, and cover the modifications with unit tests, but there are other problems as well.
For example: `TimeKeeper::formatDuration(3600)` returns `00:00`;

**Comment by kurtjunker** [comment]
Hi @Sweetchuck,

Is it possible that this fix can be merged to a new minor Version like 3.0.8?
I think that this change can also be used in the previous PHP Versions.

**Comment by Sweetchuck** [comment]
@kurtjunker This fix is already merged into 3.x, and works with PHP 7.1 - 8.1.
