### ISSUE TITLE
Error msg: Must specify access token via Authorization header...." 

### ISSUE THREAD

**Issue by judy-akers** [consolidation/robo#1098]
### Steps to reproduce
I have taken over the assignments for someone who has left our agency, and I received only bare training of how to run Robo. 

### Expected behavior
My assignment is to update the remaining Drupal 7 websites with necessary security updates for both core and modules. 

### Actual behavior
 Attempts to run robo git:deploy-github-release command results in an error of " [Development\GitHubRelease]  Must specify access token via Authorization header...." 

It does successfully do the git add, git commit, and git push origin master. But when it attempts to POST the release, that is when the error message happens. 

I have created the necessary access token on Github (for both my userid and the group userid for production updates) but I do not know which one or where to put the PAT token in order to get the release created.

I need help to set the Authorization Header with the new access token. Or documentation on how to set up and use Robo in real life.

### System Configuration
Which O.S. and PHP version are you using?
Using a MacBook Pro (MacOS Big Sur version 11.6.2) and PHP 7.4 
 
Currently using Robo 1.4.14-dev version. I would also need instructions on how to update to a newer version if that is needed.

**Comment by greg-1-anderson** [comment]
Looks like your issue is with the `git:deploy-github-release` command, which is not part of Robo core. Look for it in a RoboFile.php, or a file named *Commands.php. The implementation should also be annotated `@command git:deploy-github-release`, so you could search your project for that string.

**Comment by judy-akers** [comment]
No, really? I know it's the git:deploy-github-release command that has the problem - but I know nothing more about robo except "Run these exact commands" The robofile.php was created 3 years ago, and that person left in Dec 2019. 

I'm working in the dark here - some real help would be nice. How about re-opening this issue to start
