### ISSUE TITLE
Greg Anderson, please reopen 1099 

### ISSUE THREAD

**Issue by judy-akers** [consolidation/robo#1100]
or email me because I can't find any help on the web about Authorization Headers and robo - or how to force robo to accept new access tokens.

Please.

-- Judy A. Akers
Chief Technology Office | Innovation & Engineering
Web Platform | Development
 
Office of Information Technology Services 
3rd Fl, 50 Wolf Rd, Albany New York 12232
(518) 486-6164 | judy.akers@its.ny.gov 
support: (518) 457-3300 |  webnysupport@its.ny.gov

**Comment by greg-1-anderson** [comment]
I am sorry that you are having a hard time finding the solution to your problem; however, the Robo issue queue is only for issues that exist in Robo itself. The Robo maintainers cannot help you research problems in code outside of Robo core.

**Comment by judy-akers** [comment]
Is there significant differences in the old version 1.4.14-dev that I am using (which my repository shows as 50 lines) for bin/robo, and the newer version of the phar which has over 10,000 lines?
Is there a way to upgrade from the old version to the new one? Would it matter?

How can I get my robo to re-ask me for my userid and password/PAT? I remember the first time I ran it about 10 days ago it wanted those values.

I am not finding much help using google, and a lot of searches return "robot" instead of "robo".

Judy A. Akers
Information Technology Specialist 3 (Programming, Public Website Infrastructure)

Office of Information Technology Services
50 Wolf Road
Albany New York 12232
Contacts - desk phone: (518) 486-6164 | cell: (518) 948-1433 | ***@***.******@***.***>
www.ny.gov<http://www.ny.gov/> | support phone: (518) 457-3300 |  ***@***.******@***.***>
*Please include ***@***.***' on emails to me to ensure that in my absence, your issue is addressed by the WebNY team. Thank you! *

**Comment by greg-1-anderson** [comment]
Your issues are probably related to GitHub deprecating some access methods, not differences in Robo behavior. However, I do not know the definitive cause, or the solution.

**Comment by judy-akers** [comment]
Thank you for trying - I hate taking over for someone who did NO documentation on their code.

Judy A. Akers
Information Technology Specialist 3 (Programming, Public Website Infrastructure)

Office of Information Technology Services
50 Wolf Road
Albany New York 12232
Contacts - desk phone: (518) 486-6164 | cell: (518) 948-1433 | ***@***.******@***.***>
www.ny.gov<http://www.ny.gov/> | support phone: (518) 457-3300 |  ***@***.******@***.***>
*Please include ***@***.***' on emails to me to ensure that in my absence, your issue is addressed by the WebNY team. Thank you! *
