### ISSUE TITLE
Using a custom Robo Class

### ISSUE THREAD

**Issue by brad-jones** [consolidation/Robo#111]
In the change log it mentions: __RoboFile can be changed to any provided class.__

This is not immediately obvious to me.

Is the idea that I simply create my own custom cut down version of the ```Robo\Runner``` class.
Removing all the logic around loading the ```RoboFile.php```.

Or is there something I am missing here???

**Comment by boedah** [comment]
Maybe have a look at #95.

**Comment by brad-jones** [comment]
If I use the example from #95 I get:
Call to undefined method Symfony\Component\Console\Application::execute()

If I change ```execute()``` to ```run()``` I get a working Symfony Console Application, however no output.

I believe the correct usage would be:

```php
\Robo\Config::setOutput(new Symfony\Component\Console\Output\ConsoleOutput());
$runner = new \Robo\Runner();
$app = $runner->createApplication('ClassNameWithTasks');
$app->run($optionalInputGoesHere);
```

In the end I created my own runner.
see: https://github.com/brad-jones/robo-tasks/blob/master/src/Runner.php

**Comment by boedah** [comment]
Couldn't we add an `-f <file>` option to use a different file?

**Comment by c33s** [comment]
it would also be good having an environment variable, to store the relative path of the `RoboFile.php` which should be used 
`export ROBO_FILE=src/Robo`

**Comment by greg-1-anderson** [comment]
This has been implemented. You can use the --load-from option, or see [framework.md](https://github.com/consolidation/Robo/blob/master/docs/framework.md)
