### ISSUE TITLE
Update robo.li Website

### ISSUE THREAD

**Issue by amenk** [consolidation/robo#1110]
* Provide information how to install up-front
* Broken boken link in header https://robo.li/ Edit on github - https://github.com/consolidation/Robo/edit/master/docs/index.md

**Comment by greg-1-anderson** [comment]
The website isn't rendering correctly because it does not work with the latest version of mkdocs, and getting a working setup with an older version is hard. PRs to fix this would be welcome; however, a rebuild of the site is in progress.

**Comment by greg-1-anderson** [comment]
The new website is available at https://consolidation.github.io/website/; I need to update the configuration so this shows up at robo.li

**Comment by amenk** [comment]
@greg-1-anderson Nice new website - can you update the domain config :D ?

**Comment by amenk** [comment]
Can you please update the config, so it becomes the official page @greg-1-anderson or is there anything how we can support ? :smile:

**Comment by greg-1-anderson** [comment]
http://robo.li now points at the new website.

I don't think that updates to the Robo project update the docs here, and I am sure that the phar is not being published here yet, but at least the site is live.
