### ISSUE TITLE
Deprecation for PHP 8.1

### ISSUE THREAD

**Issue by nkazarynava** [consolidation/robo#1142]
### Steps to reproduce
In scope of PHP8.1 compatibility static analysis it was discovered some deprecations in webflo/drupal-finder codebase: 
  - line 73 vendor/consolidation/robo/src/Common/ConfigAwareTrait.php get_called_class() without argument (tag 4.0.2) 

### Expected behavior
No deprecations found when running on PHP 8.1

### System Configuration
PHP 8.1

PR has been created  https://github.com/consolidation/robo/pull/1141

**Comment by greg-1-anderson** [comment]
Thanks for the fix.
