### ISSUE TITLE
Symfony 7 support

### ISSUE THREAD

**Issue by akalineskou** [consolidation/robo#1151]
### Steps to reproduce
Tried to upgrade symfony to v7

### Expected behavior
Dependencies should resolve

### Actual behavior
Multiple dependencies from symfony and the consolidation repos are failing because of it

**Comment by larowlan** [comment]
Starting work here https://github.com/consolidation/config/pull/62

**Comment by larowlan** [comment]
https://github.com/consolidation/robo/pull/1156

**Comment by greg-1-anderson** [comment]
Now supported on the 5.x branch.
