### ISSUE TITLE
Change default branch to 5.x

### ISSUE THREAD

**Issue by captn3m0** [consolidation/robo#1159]
### Steps to reproduce
Visit https://github.com/consolidation/robo

### Expected behavior
The list of branches in the default README (https://github.com/consolidation/robo#branches) should be up to date.

### Actual behavior
Since default branch is 5.x, https://github.com/consolidation/robo#branches does not list 5.x

### Alternate Suggestion
1. Another alternative is to list 5.x in the https://github.com/consolidation/robo/blob/4.x/README.md, but that just increases maintenance. 

2. A second alternative is to move the table to the website, so [there is one single](https://endoflife.date/recommendations#publishing) link for the information. Keeping release information versioned means updates in multiple places, and that causes confusion. Happy to file a PR for the website (and further PRs to delete/link it from the README) if this sounds better.

**Comment by greg-1-anderson** [comment]
Good point; intended to do this, but forgot. Default branch is now 5.x.
