### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by mint-jar** [consolidation/robo#1162]
### Steps to reproduce
Visit robo.li

### Expected behavior
See the site.

### Actual behavior
Notification that the site can't be found.

### Workaround
I  am using http://consolidation.github.io/robo/ at the moment.

**Comment by mint-jar** [comment]
Apologies in advance if I should have reported this elsewhere :sweat_smile:

**Comment by greg-1-anderson** [comment]
@DavertMik Did the domain expire? You could transfer it to me if you wanted me to renew it annually.

**Comment by DavertMik** [comment]
@greg-1-anderson yeah, I thought I paid it but Gandi didn't send me any notice on payment failure so I was thinking that I paid for another year. I changed the payment method and it worked.
