### ISSUE TITLE
Fix "symfony/event-dispatcher" dependency in branch 5.*

### ISSUE THREAD

**Issue by dbublik** [consolidation/robo#1166]
Could you fix the "symfony/event-dispatcher" dependency for 6.*?
This line: https://github.com/consolidation/robo/blob/5.0.0/composer.json#L34

### Expected behavior
`"symfony/event-dispatcher": "^6 || ^7"`

### Actual behavior
`"symfony/event-dispatcher": "6 || ^7"`

P.S. And please create a new tag (5.0.1?) 🙏

**Comment by prudloff-insite** [comment]
I created a PR to fix this: https://github.com/consolidation/robo/pull/1169

**Comment by greg-1-anderson** [comment]
Fixed in 5.1.0. Thank for the PR.
