### ISSUE TITLE
Add multiple symfony commands

### ISSUE THREAD

**Issue by sagikazarmark** [consolidation/Robo#132]
I would like to add a bunch of symfony commands to be used in robo.

Use case: doctrine console commands used with robo

Is that possible?

**Comment by DavertMik** [comment]
sure, there is `SymfonyCommand` task (to execute commands in the same process) as well as `Exec` task to run commands in `exec`.

or you are about sending PR to have tasks prepared to work with symfony?
in this case I'd ask you to put them in standalone repo.

**Comment by sagikazarmark** [comment]
I mean something like this:
```
Class RoboTask
{
    public function __construct()
    {
         $this->addSymfonyTask(new MyCommand);
    }
}
```

Then

`$ robo my:command`

**Comment by sagikazarmark** [comment]
So tasks are created upon adding a new command and I don't have to creat them one by one.

**Comment by rclayton-the-terrible** [comment]
+1  - looking to do something similar.

**Comment by greg-1-anderson** [comment]
Try using taskSymfonyCommand with the new collection builder object.
