### ISSUE TITLE
Use Symfony Process ExecutableFinder

### ISSUE THREAD

**Issue by sagikazarmark** [consolidation/Robo#142]
Custom binary paths causes problem because most of the tasks use predefined locations to look for executables. Providing a custom path is not always a solution as in some cases one RoboFile is used by an entire team (with different paths).

**Comment by burzum** [comment]
I think instead of using ExecutableFinder (smells like overhead) we should implement a way  to use different configurations with Robo.

**Comment by sagikazarmark** [comment]
My point is that the exact path should come from a third source, not the RoboFile itself.

**Comment by greg-1-anderson** [comment]
Robo is using this as a fallback search mechanism now.
