### ISSUE TITLE
Error in readMe file

### ISSUE THREAD

**Issue by javigomez** [consolidation/Robo#160]
TaskCommand(...) mentioned here https://github.com/Codegyre/Robo/blame/master/README.md#L76
 do not exists 

![screen shot 2015-04-21 at 12 56 26](https://cloud.githubusercontent.com/assets/1375475/7250738/1e06d8e6-e825-11e4-86e5-4661f7fda3d4.png)

We should probably mention taskCodecept() instead, but not sure

**Comment by DavertMik** [comment]
Actually it was about running Symfony Commands. Sorry that was not obvious

**Comment by greg-1-anderson** [comment]
Fixed.
