### ISSUE TITLE
Composer Base Task checks fails in TravisCI

### ISSUE THREAD

**Issue by javigomez** [consolidation/Robo#164]
The Robo Composer tasks do several checks to ensure if Composer is already installed or not by:

```php
    public function __construct($pathToComposer = null)
    {
        if ($pathToComposer) {
            $this->command = $pathToComposer;
        } elseif (file_exists('composer.phar')) {
            $this->command = 'php composer.phar';
        } elseif (is_executable('/usr/bin/composer')) {
            $this->command = '/usr/bin/composer';
        } elseif (is_executable('/usr/local/bin/composer')) {
            $this->command = '/usr/local/bin/composer';
        } else {
            throw new TaskException(__CLASS__, "Neither local composer.phar nor global composer installation not found");
        }
    }
```

see: https://github.com/Codegyre/Robo/blob/master/src/Task/Composer/Base.php#L67-L79

However in TravisCI composer is located at:

```bash
$ which composer
/home/travis/.phpenv/shims/composer
```

![screen shot 2015-04-22 at 10 43 36](https://cloud.githubusercontent.com/assets/1375475/7270377/0db0044c-e8dc-11e4-8d05-b74d518919cd.png)

Somehow Robo should be able to check if Composer can be executed like:
```bash
$ composer
```
But not sure how, because this doesn't work:

```
is_executable('composer')
```

Any suggestion?

**Comment by boedah** [comment]
This also attracted my attention.
Maybe the best way would be to execute `which composer` (on Windows it would be `where composer`) and check the output.

Position: before the final `else`-clause throwing the Exception.

**Comment by gunfrank** [comment]
@javigomez, @boedah did you guys solve this in an elegant way? Any suggestions or snippets / PRs would be greatly appreciated.

**Comment by boedah** [comment]
@gunfrank did you try the method suggested in my comment above?

**Comment by gunfrank** [comment]
@boedah, I didn't, as the OS difference (which/where composer) suggest more conditionals and I'm not sure what's the right way to implement it. I mean, the goal is that we solve this and send a PR that gets accepted. However, I'm not proficient enough to do it, I suppose. 

Anyways, I'll try to make it work at least locally. If you have more time - please contribute with some example.

**Comment by gunfrank** [comment]
I came up with:
```
elseif (is_executable(exec('where composer', $output)[0])) {
            $this->command = $output[0];
}
```
before the final `else` that throws the exception.

How bad is it?

**Comment by greg-1-anderson** [comment]
Pretty sure this is working now. Re-open if it's still an issue.
