### ISSUE TITLE
Autoloader using phar file

### ISSUE THREAD

**Issue by roland-d** [consolidation/Robo#183]
Hello,

I have been trying to figure out, failed so far, how the autoloader works with the robo.phar file. It seems to never find any file I specify. All works fine with require but autoloading is preferred of course.

How would I autoload the loadTasks.php file with the robo.phar?

Thank you.

**Comment by dlancea** [comment]
I think you should create a RoboFile.php file, and load loadTasks.php into that file.

**Comment by greg-1-anderson** [comment]
This is now documented in [frameworks.md](https://github.com/consolidation/Robo/blob/master/docs/framework.md).
