### ISSUE TITLE
Git locks on Vagrant VM running Ubuntu in Windows Host

### ISSUE THREAD

**Issue by Gisleburt** [consolidation/Robo#190]
Running:
 - Windows 7
 - VirtualBox 4.3.18
 - Vagrant 1.7.3
 - PHP 5.6.10
 - Robo 0.5.3

I'm trying to write a script that download source from Git and run composer. I've made it so that it will look and see if the directory your downloading into already exists, and if it does delete it and remake it. The problem I'm having is that after running 

```php
$this->taskGitStack()
     ->cloneRepo($this->repository, $this->installDir)
     ->run();
```

I can not then delete the directory using the FileSystem.

```php
$this->taskDeleteDir($directory)->run();
$this->taskFilesystemStack()->mkdir($directory)->run();
```

 I get an error like:

```bash
[Symfony\Component\Filesystem\Exception\IOException]
  Failed to remove file "/var/www/vhosts/project/temp/.git/objects/pack/pack-cf41b331af2462dea363876a266f82ad3a4ae804.pack".
```

What's interesting is that I
1. Don't get this when I use the script away from the Windows share.
2. Don't get this when I do each step in bash
3. Don't get this when I run the following script in the same location    
```php
<?php
`git clone ssh://user@repo.uri/project temp`;
`rm -r temp`
```

Any thoughts? 

I can probably work around it so it's not the end of the world, but I'd be suprised if I'm the only one using Vagrant + Ubuntu in Windows as a development environment and work arounds aren't great when mapping to production. :wink:

**Comment by boedah** [comment]
Uh, shared folders on a Windows host can drive you insane (max path length error with node_modules anyone?).

So `var/www` is you shared directory with the host?

1. so `$this->installDir` and `$directory` are not the shared dir anymore?
1. inside the shared dir? This is strange...
1. so `temp` is also inside the shared dir?

We had this issue (but not limited to Robo) when some process on the Windows host seem to have locked the files (e.g. Git Bash, PhpStorm, Explorer)...

Does it work if you close these applications on the host?

Can you clone in one Robo cli call and delete in another Robo cli call? So the issue is only if clone and delete are happening in the same process?

**Comment by Gisleburt** [comment]
My explaination isn't very good. :stuck_out_tongue_closed_eyes:  I'll write a script to demonstrate it.

**Comment by Gisleburt** [comment]
So, with nothing open in PhpStorm, Windows Explorer, SourceTree or any other tools:

**composer.json**
```json
  "require" : {
    "codegyre/robo" : "~0.5.3"
  },
  "config" : {
    "bin-dir" : "bin"
  }
}
```

**RoboFile.php**
```php
<?php
/**
 * This is project's console commands configuration for Robo task runner.
 *
 * @see http://robo.li/
 */
class RoboFile extends \Robo\Tasks
{
    // define public methods as commands

    public function demo($opts = ['yes|y' => false])
    {
        $directory = 'temp';
        if(!is_dir($directory)) {
            if($opts['yes'] || $this->confirm("$directory does not exist. Create it?")) {
                $this->taskFilesystemStack()->mkdir($directory)->run();
            }
        }

        $directory = realpath($directory);
        if(count(scandir($directory)) > 2) {
            if($opts['yes'] || $this->confirm("$directory is not empty. Empty it?")) {
                $this->taskDeleteDir($directory)->run();
                $this->taskFilesystemStack()->mkdir($directory)->run();
            }
        }

        $this->taskGitStack()
            ->cloneRepo('ssh://foundrygit@gitserver.thefoundry.co.uk/madewitmischief', 'temp')
            ->run();
    }

}
```

Example Test:
```bash
$ while bin/robo demo -y; do :; done
 [FileSystem\FilesystemStack] mkdir ["temp"]
 [Vcs\GitStack] Running git commands...
 [Vcs\GitStack] git clone ssh://foundrygit@gitserver.thefoundry.co.uk/madewitmischief temp
Cloning into 'temp'...
Checking out files: 100% (1393/1393), done.
 [Vcs\GitStack] Done in 42.561s
 [FileSystem\DeleteDir] Deleted /www/temp/temp...
 [FileSystem\FilesystemStack] mkdir ["\/www\/temp\/temp"]
 [Vcs\GitStack] Running git commands...
 [Vcs\GitStack] git clone ssh://foundrygit@gitserver.thefoundry.co.uk/madewitmischief temp
Cloning into 'temp'...
Checking out files: 100% (1393/1393), done.
 [Vcs\GitStack] Done in 35.831s
 [FileSystem\DeleteDir] Deleted /www/temp/temp...
 [FileSystem\FilesystemStack] mkdir ["\/www\/temp\/temp"]
 [Vcs\GitStack] Running git commands...
 [Vcs\GitStack] git clone ssh://foundrygit@gitserver.thefoundry.co.uk/madewitmischief temp
Cloning into 'temp'...
Checking out files: 100% (1393/1393), done.
 [Vcs\GitStack] Done in 35.401s



  [Symfony\Component\Filesystem\Exception\IOException]
  Failed to remove directory "/www/temp/temp/public/static/admin/js/tinymce/plugins/visualblocks".

```

The number of goes it takes to break varies. The file can no longer be deleted from the Guest at all, but can be deleted from the Host fine.

**Comment by Gisleburt** [comment]
So the issue is very intermittent and for a while I thought it had actually gone away. However, I was able to recreate it like this:

**composer.json**
```json
{
  "require" : {
    "codegyre/robo" : "~0.5.3"
  },
  "config" : {
    "bin-dir" : "bin"
  }
}
```

**RoboFile.php**
```php
<?php
/**
 * This is project's console commands configuration for Robo task runner.
 *
 * @see http://robo.li/
 */
class RoboFile extends \Robo\Tasks
{
    // define public methods as commands

    public function demo($opts = ['yes|y' => false])
    {
        $directory = 'temp';
        if(!is_dir($directory)) {
            if($opts['yes'] || $this->confirm("$directory does not exist. Create it?")) {
                $this->taskFilesystemStack()->mkdir($directory)->run();
            }
        }

        $directory = realpath($directory);
        if(count(scandir($directory)) > 2) {
            if($opts['yes'] || $this->confirm("$directory is not empty. Empty it?")) {
                $this->taskDeleteDir($directory)->run();
                $this->taskFilesystemStack()->mkdir($directory)->run();
            }
        }

        $this->taskGitStack()
            ->cloneRepo('https://github.com/Codegyre/Robo.git', 'temp')
            ->run();
    }

}
```

**Example test:**
```bash
daniel@vagrant-ubuntu-trusty-64:/www/temp$ while bin/robo demo -y; do :; done
 [FileSystem\FilesystemStack] mkdir ["temp"]
 [Vcs\GitStack] Running git commands...
 [Vcs\GitStack] git clone https://github.com/Codegyre/Robo.git temp
Cloning into 'temp'...
 [Vcs\GitStack] Done in 24.058s
 [FileSystem\DeleteDir] Deleted /www/temp/temp...
 [FileSystem\FilesystemStack] mkdir ["\/www\/temp\/temp"]
 [Vcs\GitStack] Running git commands...
 [Vcs\GitStack] git clone https://github.com/Codegyre/Robo.git temp
Cloning into 'temp'...
 [Vcs\GitStack] Done in 21.572s



  [Symfony\Component\Filesystem\Exception\IOException]
  Failed to remove file "/www/temp/temp/.git/objects/pack/pack-708f789270352ee5eb52b65b1642c2744f5de2c1.pack".



demo [-y|--yes]


```

Once the problem has occured I can not remove the files from the Guest at all, but can be removed from the Host. As a control, I also used this

```bash
daniel@vagrant-ubuntu-trusty-64:/www/temp$ while git clone https://github.com/Codegyre/Robo.git temp && rm -r temp; do :; done
```

And that seemed to work without incident.

Note: the file system of `/www` is `vboxsf` and is linked to a Windows 7 NTFS file system.

I can solve this problem by installing to `/tmp` or somewhere else in the Guest that doesn't use this file system. Or I could probably use NFS for /www which is probably a better option generally. I still thought you should be aware of the issue.

**Comment by greg-1-anderson** [comment]
Closed due to lack of activity.
