### ISSUE TITLE
Execute instantiated classes

### ISSUE THREAD

**Issue by oscarotero** [consolidation/Robo#197]
Hi. I'd like to execute a custom Robo class but I need to pass some arguments to the contructor. I see Robo allows to use custom classes (https://github.com/Codegyre/Robo/blob/master/src/Runner.php#L67) but it only accepts the classname. I would be very grateful if this is changed to accepts also objects. This makes the library more flexible to prepare the class before to be handled by Robo (with constructor arguments and properties).
Thank you!

**Comment by greg-1-anderson** [comment]
This is fixed, and is now documented in [frameworks.md](https://github.com/consolidation/Robo/blob/master/docs/framework.md).
