### ISSUE TITLE
Set working directory for Robo?

### ISSUE THREAD

**Issue by burzum** [consolidation/Robo#219]
We have an application that has plugins that are included via composer. We now would like to use the Robo install of the main application to run the build scripts for each of the plugins.

The issue is that Robo seems to only detect the Robo.php from the applications root. Is there any way to set Robos working directory to one of the plugins in a subfolder?

**Comment by DavertMik** [comment]
No. But this can be implemented

**Comment by boedah** [comment]
Could you use the main RoboFile to loop over plugin directories and execute a `cd vendor/plugin-1 && robo plugin1-task` for each one?

**Comment by netstyler** [comment]
@boedah 
this works only if robo is installed global on your system.

**Comment by netstyler** [comment]
@DavertMik 
:+1:  if someone could implement this

**Comment by boedah** [comment]
@netstyler: you could get the absolute path to the `vendor/bin/robo` first and use it.

There could be many ways to do it.

* use some tricks using #95 
* implement `-f some/other/RoboFile.php` (see https://github.com/Codegyre/Robo/issues/111#issuecomment-114901672)

@burzum: could you elaborate more on the structure of your plugins and what exactly you are trying to achieve?

* call tasks from one plugins RoboFile one at a time? ("Is there any way to set Robos working directory to one of the plugins in a subfolder"
** this would be this issue or #111
* run a task from the main RoboFile which runs tasks from one or more plugin RoboFiles? ("use the Robo install of the main application to run the build scripts for each of the plugins")
** this could be done (I think) using an `ExecTask` in the main RoboFile (and implementing `-f Another/RoboFile.php` would also help here and make it more expressive)

**Comment by DavertMik** [comment]
Started working on it. Will be released soon

**Comment by kylephp** [comment]
@DavertMik @boedah  google brought me here, I have 2 different composer.json files: 1 in current working dir and 1 in sub dir. How can I run `composer install` for both?

**Comment by boedah** [comment]
@kylephp I would simply change the working directory (and set it back afterwards) with http://php.net/manual/function.chdir.php between the two composer install tasks.

**Comment by kylephp** [comment]
@boedah Thanks for answering. I've just tried that approach but could not make it. Steps I did:
- I run `vendor/bin/robo run:some-function` from command line (current working dir where Robofile.php file placed)
- Inside `runSomeFunction` function of Robofile.php, I just simply used: `$this->getComposer()` `$this->taskComposerInstall()->run()` to install dependencies for current working dir. But for the sub-dir, I failed to do that even with the `chdir` which you mentioned above

**Comment by kylephp** [comment]
update: I copied `composer.json` to sub-dir by using $this->_exec('cp composer.json subdir') before running:  `$this->getComposer()` and `$this->taskComposerInstall()->run()`

**Comment by kylephp** [comment]
update 2: it worked after I run: `vendor/bin/robo run:some-function` for the 2nd time, means there's `Nothing to install or update` on current working dir

**Comment by greg-1-anderson** [comment]
This has been implemented.

**Comment by ivangretsky** [comment]
> This has been implemented.

Great! Couldn't find how in the docs. I am probably missing something obvious. Could you please give an example how to do it?
How do I set custom working directory for Robo?
