### ISSUE TITLE
Improve usability of taskExecStack

### ISSUE THREAD

**Issue by Koc** [consolidation/Robo#223]
There is no way to escape arguments/options of command. It would be usable put instances of `Command` or etc to `exec` method.

**Comment by Koc** [comment]
Also there is no way change directory only for one command of the stack. `dir` method changes cwd for all commands in the stack. So I should write something like

```
->exec('cd ~/vhosts/metalloprokat-markup.dev && hg up default -C && composer install')
```

**Comment by DavertMik** [comment]
Please start contributing to improve that behavior. Thanks!

**Comment by greg-1-anderson** [comment]
Escaping of arguments and options has been improved. PRs for further improvements would be appreciated.
