### ISSUE TITLE
Open a browser on run phpServer

### ISSUE THREAD

**Issue by oscarotero** [consolidation/Robo#225]
Hi.
It would be great to have an option to open a browser with the http server. Something like:
```php
$this->taskServer(8000)
    ->dir('site')
    ->arg('site/index.php')
    ->open('about-me')
    ->run()
```
This runs the server and open a browser with the url http://127.0.0.1:8000/about-me. The code for this may be [something like this](https://github.com/composer/composer/blob/master/src/Composer/Command/HomeCommand.php#L116)

**Comment by DavertMik** [comment]
Opening browser can be unrelated to PHPServer. Not sure where to put it actually...
This looks like a nice hook and probably can be implemented as standalone task but I don't know where to put it. Probably If you could make a PR with it it can be added into Base

**Comment by oscarotero** [comment]
Yes, no problem.

**Comment by oscarotero** [comment]
I just created the PR with OpenBrowser task #235

**Comment by oscarotero** [comment]
Hi again.
Now that OpenBrowser task is released, I like to know how to create a php server and open a browser window with the page. Seems that open a browser after the server starts is not allowed.

For example:
```php
$this->taskServer(8000)->run();
$this->taskOpenBrowser('http://localhost:8000')->run();
```
This code doesn't work because while the server is running, the php don't execute the next tasks.

```php
$this->taskServer(8000)->background()->run();
$this->taskOpenBrowser('http://localhost:8000')->run();
```
This doesn't work either, because after open the browser the php execution ends, and the server stops.

Is any way to do this? For example, something like this should be great:

```php
$this->taskServer(8000)
    ->onStart(function () {
        $this->taskOpenBrowser('http://localhost:8000')->run();
    })
    ->run();
```

**Comment by stefanhuber** [comment]
This would be totally necessary. Anyway to achieve this ????

**Comment by dustinleblanc** [comment]
I actually have had occasion in the past to want to start a task such as the server and then complete the task once all other tasks were run (tests in my case). The above sounds particularly interesting; the variant in my case would be something like:

```php
$this->taskServer(8000)
    ->while(function () {
        $this-taskCodeCept->run();
   })->run();
```

@DavertMik @greg-1-anderson what do you guys think?

**Comment by greg-1-anderson** [comment]
Drush [opens the browser before it starts the php built-in webserver](https://github.com/drush-ops/drush/blob/7eabf7536a9c1ec19a76fa01cbdb6b6be5a06a12/commands/runserver/runserver.drush.inc#L131).

@dustinleblanc: That sounds like a really good feature. The challenge is that the php server won't return once you start running it.  To do this, you'd have to [fork a thread](http://php.net/manual/en/class.thread.php), and call proc_open inside the thread (and [manage IO like drush backend invoke does](https://github.com/drush-ops/drush/blob/7eabf7536a9c1ec19a76fa01cbdb6b6be5a06a12/includes/backend.inc#L343)), or maybe launch the process in the background.  It's a little inconvenient to [handle background processes in php](https://florian.ec/articles/running-background-processes-in-php/), though. I think the Symfony Process component might be helpful here.

It would be cool if someone worked through these issues and got something working.

**Comment by dustinleblanc** [comment]
Sounds like a project worth pursuing. I'll take a look at the process component and the tidbits of info you just gave and see if I can grok the concepts well enough to prototyping it. Thanks for the info and opinion!

**Comment by greg-1-anderson** [comment]
This feature would still be welcome, but closing out this issue.
