### ISSUE TITLE
Future of Robo - what purpose should Robo serve?

### ISSUE THREAD

**Issue by boedah** [consolidation/Robo#230]
Through its lifespan Robo evolved from a simple task runner to a general purpose, one-for-all tool.

@DavertMik what is your vision for Robo? What are its core features?

Especially with all the Asset-Tasks added lately (just saw the PR for image minification):
How can Robo compete (and does it want to compete) with something like the Node.js ecosystem (gulp et al.)?
Have not tested it, but would say that compiling a complex SASS suite would take significantly longer (even longer than ruby-sass?) than compiling it with gulp.

I would question whether we should re-implement (and support!) long-living Node modules in PHP.

What is your opinion about that?

**Comment by gabor-udvari** [comment]
My motivation to contribute all the new tasks was so I can create a PHP only version of the [Sage](https://github.com/roots/sage) Wordpress starter theme, which I named [Phlomis](https://github.com/gabor-udvari/phlomis). After switching my Wordpress workflow to use Composer for installing and updating the core and plugins I found it very frustrating that I needed to use Node, npm and gulp for building a Wordpress theme. I am still missing some features, like compiling with libsass and updating the browser, but I think the current state is promising.

Comparing the two building processes, Sage looks like this:
```shell
git clone https://github.com/roots/sage.git && cd sage
npm install
bower install
gulp build
```

Phlomis looks like this:
```shell
git clone https://github.com/gabor-udvari/phlomis.git && cd phlomis
composer.phar install
vendor/bin/robo build
```

Time required for the above commands with empty cache:

<table>
<tr><td>Sage</td><td>Phlomis</td></tr>
<tr><td width="50%">
<pre>
time npm install
real    5m13.584s
user    5m29.869s
sys     0m57.984s

time bower install
real    0m11.879s
user    0m5.250s
sys     0m1.268s

time gulp build
real    0m25.906s
user    0m24.060s
sys     0m1.383s
</pre>
</td>
<td>
<pre>
time composer.phar install
real    2m56.736s
user    0m25.762s
sys     0m4.583s

time vendor/bin/robo build
real    0m5.597s
user    0m5.417s
sys     0m0.107s
</pre>
</td></tr>
</table>

The ability to use Composer + Robo for assets makes the learning curve for webdevs with PHP background much easier. I think this familiarity outweighs the lack of performance or features. If you feel that Robo is getting bloated I am ok to keep the extra tasks out of the repository and maintain them as a standalone repo and publish them with `robo-` prefix on Packagist (just like the readme says).

**Comment by boedah** [comment]
`gulp build` being 5 times slower than `robo build` seems strange.
We came down from 25 seconds using Grunt + Ruby Sass to under a second using gulp and gulp-sass (=libsass).

Do not take this as criticism, I find more options to choose from very helpful.
And sure, for simple tasks, using PHP may be an option.

But the more dependencies are in core Robo, the more they have to be maintained, bug fixed, updated if the underlying libraries change, etc...

Just wanted to have the opinion of @DavertMik about that.

**Comment by burzum** [comment]
Speed is second for us, what matters is that our tool uses php and not npm+bower+gulp+node+wtf...

But I agree and think that Robo grows a little wild and many tasks have a very different quality and sometimes even API. I would split robo in multiple repos, like robo-core, robo-assets, robo-whatever, you get the idea.

**Comment by boedah** [comment]
> If you don't want to maintain your own SASS/LESS/JS/Whatever-Compiler-Minifier then you'll use a lib, that's what they all do. So you won't get around the dependencies.

@burzum: yes, that's true. Because of that I was suprised that `leafo/scssphp` needs to be added to composer. A SASS compiler written in PHP. Personally I would not recommend anyone to use this because of compatibility issues.
Not so much, if it would be https://github.com/sensational/sassphp (which uses the official libsass), but seems not to be easily setup.

> what matters is that our tool uses php and not npm+bower+gulp+node+compass+wtf... I've recently had the joy to set up such a project and spend a lot time to fix some problems with the package managers and getting the whole stuff built. I really prefer to stick to php, because the app is php, we already have composer and we know php better than JS.

Yes, this with the above reminds me a little bit of NIH...
We should not re-invent everything in PHP, just because we can.

But you can of course - and this is how we do it - let Robo be the "main" task runner, and orchestrate the other ones for you.
@DavertMik also made the first example do this: https://github.com/Codegyre/Robo/issues/51#issuecomment-51996671

But I think if we do not split the additional tasks out (like I was advised to do it with https://github.com/boedah/robo-drush), we will soon have issues for Robo popping up with people saying: "Robo does not understand this and that SASS construct."....

I think Robo should only handle the absolute core functionality (directory / file handling, ZIP, TAR, PHAR, ...) - and this really well.

Just my two cents...

**Comment by Benoth** [comment]
I hate to say this because I do not like npm / bower (especially if you have to use Windows, what a pain in the a...), but for this kind of front-end tasks (SCSS, LESS, Minify, etc.), there are many more quality packages in JS (or at least, features rich), we must admit it.

However, personally I think that the feature list is one of the Robo strength's : You get the phar file and you get almost everything you can need for a task runner. I just think that, if Robo do something, it must do it well and at 100%. And I think that's globally fine for a lot of features, but that's not the case with assets management (it indeed miss a lot of features easily found with gulp : livereload, compass management, map files, etc).

Just my two cents... too ;) (and by the way, thanks for the hard work on Robo, I'm using it almost every day !)

**Comment by Falc** [comment]
> How can Robo compete (and does it want to compete) with something like the Node.js ecosystem (gulp et al.)?

It is difficult to compete with such a huge ecosystem, but the most common tasks can be replaced easily. In fact, some of them are already covered by Robo.

> I agree and think that Robo grows a little wild and many tasks have a very different quality and sometimes even API. I would split robo in multiple repos, like robo-core, robo-assets, robo-whatever, you get the idea.

+1

> I think Robo should only handle the absolute core functionality (directory / file handling, ZIP, TAR, PHAR, ...) - and this really well.

+1

In my opinion it would be very interesting to split Robo into many "single-responsibility" packages. The [asset related tasks](http://robo.li/tasks/Assets/) have several "additional dependencies" that must be added manually to composer. Having something like *robo-css-minify*, *robo-js-minify*, *robo-less*, *robo-html-prettify*... can prevent that. They could also be moved to a GitHub organization, maintained by different people and have their own specific issues. There are a lot of unrelated open issues right now, and that can become messy.

Apart from that, I find very interesting to run tasks remotely through the SSH task. I use it for simple server management.

**Comment by DavertMik** [comment]
Finally I got to this issue. Sure it is an interesting question should Robo be split into various tasks or keep all of them inside. For now I don't see real reason to not include everything we can into core. Even huge PRs like `ImageMinify` is still only one class added. Why not to leave it? From my experience it is much easier to maintain one big repo then lots of small ones. Actually I don't even have time to get to review issues from all repos I maintain, so probably, I'd like to have everything in one place. The second reason is that Robo itself has almost 1000 stars and looks like a trusted GitHub repo, if we move some tasks to other repositoiries they will have 1-5 stars and it will be hard to rely on those numbers. It's just a matter of trust, but while we can keep it in core it will be much easier it to maintain. 

But sure one day I see Robo to be decoupled like Grunt and Gulp. For now I don't see that much PRs for make it reasonable.

----

For now I'd like to have a Robo Team to be organized, as you seen I don't have much time to pay attention to Robo. Right now there are me and @boedah but we need more people to propose ideas and make this project move. I also don't use Robo to compile assets. So we need someone with that experience.

As for Robo 1.0 I'd like to have 

* stable tasks and output API
* commands API
* web version (why not?)
* move some outstanding tasks to threir repos

So I'd like to have Robo to be also a platform for building other applications, like it was for RoboCI. As you may see I added predefined commands with traits https://github.com/Codegyre/RoboCI/blob/master/RoboFile.php#L6 => https://github.com/Codegyre/RoboCI/blob/master/src/Command/CI.php. And I'd like to extend this idea to have packages of predefined commands which can be easily installed and used. 

Also Robo may evolve as a platform for generators (like Yeoman). 
These things should be discussed.

**Comment by greg-1-anderson** [comment]
For Robo 1.0, I would also suggest support for Psr/Log.  I'd expect a web version to be a separate project, if provided.

I'm willing to co-maintain here.

**Comment by greg-1-anderson** [comment]
I mis-spoke above. Psr/Log support in Robo would be great to have, but it should not be considered a prerequisite for tagging a 1.0 release of Robo.

In the past, there was the feeling that a 1.0 release of a project was some sort of declaration of usability or "completeness". By SemVer reckoning, though, tagging major versions is more of a *contract* or *promise* of compatibility.  When breaking changes are introduced into a project, its major version is bumped up by one, which serves to advertise that breaking changes were introduced.  In contrast, 0.x or "dev" versions of a project might break b/c on every release.

Avoiding a stable release obviates much of the benefits of semantic versioning.  As illustrated in #257, it is very difficult to follow best practices for how to stipulate the versions of your dependents in composer.json and composer.lock, and how those should be tested.  It is really hard / impossible to do this in a single branch if you want to do something such as maintain compatibility with an older version of php, when one of your dependencies has moved on and no longer supports it. The right way to handle this situation is to have a separate branch.  In the current instance, the 1.x and 2.x branches of Robo could remain identical (with every commit on 2.x / master being backported to 1.x), with the exception that the 1.x branch tests php 5.4, and the 1.x branch depends on Symfony 2.5 components.

**Comment by greg-1-anderson** [comment]
Good discussion in this issue. Please bring up any outstanding or new items in a separate issue, or better yet, PR. ;)
