### ISSUE TITLE
Mirror Task needs some additional configuration options

### ISSUE THREAD

**Issue by stefanhuber** [consolidation/Robo#247]
I want to mirror, but just override and not delete. This is configurable for underlying Symfony, but not inside Robo.

All options might be set to true by default, but the option to override them are necessary, in my opinion...

https://github.com/Codegyre/Robo/blob/master/src/Task/FileSystem/MirrorDir.php#L27

```
$this->taskMirrorDir(['src/upload' => 'www'])
    ->delete(false)
    ->run();

```

**Comment by greg-1-anderson** [comment]
Closed due to lack of activity. #248 would still be welcome, if updated for latest master and enhanced with tests.
