### ISSUE TITLE
[Ssh] No tty present and no askpass program specified

### ISSUE THREAD

**Issue by roma-glushko** [consolidation/Robo#358]
I've tried to configure postfix on my removed host via SSH:

public function configEmailForwarding()
    {
        $this->taskSshExec('s', 'dev')
            ->port(self::PORT)
            ->exec('cat /etc/postfix/virtual_forwardings.pcre')
            ->exec('cd /var/spool/postfix/pid')
            ->exec('sudo rm master.pid')
            ->exec('sudo service postfix restart')
            ->run();
    }

Then I've executed this action:
`robo.phar config:email-forwarding` 
and I've got the following issue:

> sudo: no tty present and no askpass program specified

So It couldn't show me request for password. 
Any ideas why?

**Comment by greg-1-anderson** [comment]
Out of scope for this issue queue.
