### ISSUE TITLE
Download phar over https

### ISSUE THREAD

**Issue by mbohal** [consolidation/Robo#362]
In the installation directions users are advised to install phar over http. Would it please be possible to provide a https link?

I need to run some tasks after deploy to production server and I'm reluctant to install from an unsecured source.

**Comment by DavertMik** [comment]
Yes, this should be done

**Comment by greg-1-anderson** [comment]
While the primary installation location, http://robo.li/robo.phar is http-only, there are now https download links available at https://github.com/consolidation/Robo/releases.

The github releases are fine if you'd like to download a **specific** Robo release. We do not have a secure URL for the **latest** Robo release at the moment, though. For deployment tasks, perhaps downloading from a specific release is more reliable anyway.

**Comment by mbohal** [comment]
Thank you
