### ISSUE TITLE
How to make Robo ssh accepting pipes (|) and redirects (<)?

### ISSUE THREAD

**Issue by vitalyspirin** [consolidation/Robo#367]
How to make ssh to accept input from a file (ex: 'ssh ... < commands.sh') and from previous command through pipe (ex: 'cat commands.sh | ssh ... ')?

I overloaded \Robo\Task\Remote\Ssh::sshCommand($command) adding there this chunk of code:

```php
if (trim($command)[0] == '<') {
    $sshCommand = "ssh{$sshOptions} {$hostSpec} {$command}";
} elseif (substr(trim($command), -1) == '|') {
    $sshCommand = "$command ssh{$sshOptions} {$hostSpec}";
} else {
    $sshCommand = "ssh{$sshOptions} {$hostSpec} '{$command}'";
}
```
Now you can do
```php
(new Ssh($host, $user))->exec('< commands.sh')->run();
```
or
```php
(new Ssh($host, $user))->exec('cat commands.sh|')->run();
````
Is there a standard way to do it in Robo?

**Comment by greg-1-anderson** [comment]
I don't think it should work like this. If we want to support a facility for pipes and input redirection, it should be done via chained method initializers, not by inspecting characters in the command string.
