### ISSUE TITLE
Comparing to Phake and Supporting Streams

### ISSUE THREAD

**Issue by CMCDragonkai** [consolidation/Robo#41]
How does this compare to Phake (not the mocking one)?

Also do you have plans to support streams similar to Gulp?

* https://github.com/fzaninotto/Streamer
* https://github.com/reactphp/stream
* https://github.com/rkrx/php-streams

**Comment by boedah** [comment]
@DavertMik I do not mean yml specifically, but using something like *_Config from Zend, Symfony or Laravel?
Sure, just for executing a `composer install` i will not need this.
But if my tasks do some more work internally, I could easily configure behaviour using config files.
We use it to configure our deploy task for different environments.
Each environment has an own config file (which ís automatically loaded) and overwrites some settings used by the task.

**Comment by burzum** [comment]
:-1: on using YAML, it's a useless overhead. Honestly, I never understood why you have to use YAML or ini files when you can simply use plain php.

@DavertMik I guess an example of the use of streams could be compressing or decompression an archive or copying a really large file and track it's process. I would have to look it up myself right now but I think thats probably a good example.

**Comment by dlancea** [comment]
+1 for streams.

Right now I need to do maintenance on a tmp directory (create and clear) for sake of having to write the files to and read from. It would be nice to do:

```php
$this->taskConcat([
		'js/lib/bootstrap/bootstrap.js',
		'js/lib/backbone/backbone.js',
		'js/lib/backbone/underscore.js',
	])
	->taskMinify()
	->type('js')
	->to('min/js/vendor.js')
	->run();
```

instead.

**Comment by greg-1-anderson** [comment]
Latest version of Robo has something partway to this; tasks can be chained, but at the moment, the results of one task do not get passed to any of the parameters of the next task.
