### ISSUE TITLE
collection->addCode() always terminates with non-zero exit code

### ISSUE THREAD

**Issue by Sweetchuck** [consolidation/Robo#422]
The `addCode()` always exists with non-zero exit code.

```php
class RoboFile
{
  public function myFoo()
  {
    $cb = $this->collectionBuilder();
    $cb->addCode(function () {return 0});

    return $cb;
  }
}
```

Then run in the console:
`$ robo my:foo`
`$ echo $?`
> 1

I tried several combinations, for example 
* `$cb->getCollection()->addCode();`
* `return $cb;`
* `return $cb->getCollection();`
* `return $cb->getCollection()->run();`

Robo version 1.0.0-RC1

**Comment by greg-1-anderson** [comment]
I cannot reproduce -- although I did have to add a `;` after `return 0` to make the php code valid.  Once I did this, then I found that my exit code was 0 for `return 0;`, and 1 for `return 1;`.

Perhaps you just made a typo?  Try again with Robo 1.0.0-RC2.

**Comment by pingers** [comment]
Couldn't reproduce using:
```
  public function myFoo()
  {
    $cb = $this->collectionBuilder();
    $cb->addCode(function () {return 0;});

    return $cb;
  }
```
```
$ php ~/projects/Robo/robo.phar --version
Robo version 1.0.0-RC1
$ php ~/projects/Robo/robo.phar my:foo
$ echo $?
0
```

**Comment by greg-1-anderson** [comment]
Presumed working; please re-open with more info if still having problems.
