### ISSUE TITLE
Implementing Facade design pattern for RoboFile.

### ISSUE THREAD

**Issue by vitalyspirin** [consolidation/Robo#441]
Now the way it's recommended for implementation is fully implementing functions inside RoboFile class. It's convenient for usage from command line but not convenient for hooking up from another PHP library.

Command line interface is supposed to return information which is human readable. However if the function is called from another PHP module then it would be convenient to get back objects (i.e. Result) instead of user friendly message.

I think it could be achieved by using Facade design pattern and moving implementation to another class (for example, RoboFileImplementation) whereas in RoboFile functions there will be only entry points with calls to functions in RoboFileImplementation class. In this case Robo framework can be easily used both from CLI and from other PHP modules.

**Comment by DavertMik** [comment]
I think you can do that already.
If we disable output in container then we can call functions as regular PHP code. @greg-1-anderson what do you think?

**Comment by greg-1-anderson** [comment]
@vitalyspirin / @DavertMik Yes, this is already supported.  The example Robo files all call $collection->run(), but if they just return $collection, then the runner will run the collection. The advantage of doing it that way is that you can call your command functions from non-cli entrypoints (potentially -- some commands might use IO, etc., but if they just use tasks, they can be used), and also, you can support hooks to fix up the task collections after they are returned from the command.

This is what Drush is doing / in the process of adopting.

The Robo example files just return ->run() for clarity, but it could go the other way.

**Comment by greg-1-anderson** [comment]
Oh, I didn't answer the question about disabling output. If you are using tasks, then all you need to do is provide a PSR-3 logger, and all task output will be sent there. You can then decide how to present this information to the user (e.g. in status dialogs). 

If you have a command that uses IO, then yes, you can inject a null output object into the commandfile, but I think it's better to only use code intended to be used in both environments.

**Comment by vitalyspirin** [comment]
Methods of RoboFile support one-character shortcuts in its parameters. You can't easily call such methods  from PHP code. Currently it's possible to manually move implementation to RoboFileImplementation class and call those functions from PHP code. If Robo official documentation would recommend such approach it would make life of many programmers easier.

**Comment by greg-1-anderson** [comment]
Sounds reasonable; a PR would be welcome.

**Comment by greg-1-anderson** [comment]
I think any such documentation would best go in https://github.com/consolidation-org/Robo/blob/master/docs/framework.md; if using Robo in its default mode (with a single RoboFile.php at the cwd, or identified via `-f`), then it wouldn't be convenient to inject a separate RoboFileImplementation object into the RoboFile. Calling code in a RoboFile from another php application is something most likely in the "Robo as a Framework"-type of scenario.

**Comment by vitalyspirin** [comment]
Initially in our project Robo was used as a CLI application. Then at some point it became necessary to call those commands from another PHP app. By then RoboFile had already many functions and it was inconvenient to refactor it especially since there were no tests.

**Comment by greg-1-anderson** [comment]
There are examples of testing RoboFiles in the Robo tests now.

**System Under Test:**
[TestRoboFile.php](https://github.com/consolidation-org/Robo/blob/master/tests/src/TestRoboFile.php)

**Example tests:**
[testRunnerTryArgs](https://github.com/consolidation-org/Robo/blob/master/tests/unit/RunnerTest.php#L92)
[testSymfonyStyle](https://github.com/consolidation-org/Robo/blob/master/tests/unit/RunnerTest.php#L109)
[testRunnerTryError](https://github.com/consolidation-org/Robo/blob/master/tests/unit/RunnerTest.php#L116)

These could be used as an example for others who wanted to write tests for their own RoboFiles.

I would expect that it would be normal for folks to start off with a very simple RoboFile. If it gets too large or complex, refactoring becomes important. [Scrutinizer](https://scrutinizer-ci.com/g/consolidation-org/Robo/) is a good tool for monitoring this situation.

**Comment by greg-1-anderson** [comment]
Good suggestions here, but I think this is mostly in the domain of the user. Feel free to submit a PR if you have documentation suggestions.
