### ISSUE TITLE
Running tasks with the same names as dirs

### ISSUE THREAD

**Issue by sehanko** [consolidation/Robo#452]
Got error on tasks when task name is same as folder.
Robo RC1, RC3, Robo-beta

Steps to reproducre

1. Create folder (ex. build)
2. Create task in robo
`
public function build() {}
`
3. Run robo task

Follow to exception:
```php
ERROR: fopen(build): failed to open stream: Permission denied
in phar://.../robo.phar/src/Runner.php:249

PHP Warning:  fopen(build): failed to open stream: Permission denied in phar://.../robo.phar/src/Runner.php on line 249
PHP Stack trace:
PHP   1. {main}() ...\robo.phar:0
PHP   2. Robo\Runner->execute() ...\robo.phar:22
PHP   3. Robo\Runner->shebang() phar://.../robo.phar/src/Runner.php:88
PHP   4. Robo\Runner->isShebangFile() phar://.../robo.phar/src/Runner.php:223
PHP   5. fopen() phar://.../robo.phar/src/Runner.php:249
```

**Comment by greg-1-anderson** [comment]
Cannot reproduce. Does this also happen for you if you use the master branch (git clone + composer install)?  What platform are you using?

**Comment by sehanko** [comment]
Sorry for long answer. Using windows 10
Doing git clone master + composert install. Added to existing Robo file task "tests" and this situation reproduced

```php
ERROR: fopen(tests): failed to open stream: Permission denied
in ...\Robo\src\Runner.php:247

PHP Warning:  fopen(tests): failed to open stream: Permission denied in ...\Robo\src\Runner.php on line 247
PHP Stack trace:
PHP   1. {main}() ...\Robo\robo:0
PHP   2. Robo\Runner->execute() ...\Robo\robo:20
PHP   3. Robo\Runner->shebang() ...\Robo\src\Runner.php:90
PHP   4. Robo\Runner->isShebangFile() ...\Robo\src\Runner.php:221
PHP   5. fopen() ...\Robo\src\Runner.php:247
```

**Comment by greg-1-anderson** [comment]
Looks like this was a Windows-specific issue. I could not reproduce on Linux, but I made a fix that I expect should clear up your problem.  Please try again with the latest master, and LMK if you still have problems.

**Comment by sehanko** [comment]
On master branch this problem gone. Thanks!
