### ISSUE TITLE
Arguments aren't escaped by src/Common/CommandArguments trait

### ISSUE THREAD

**Issue by Sweetchuck** [consolidation/Robo#467]
The `\Robo\Common\CommandArguments::args()` doesn't escape the the arguments because it doesn't use the return value of `array_map()`.
The original `$args` variable is untouched by the `array_map()`

https://github.com/consolidation/Robo/blob/1908cec67c6278d6d21535f14ca403cc860d4518/src/Common/CommandArguments.php#L36

**Comment by greg-1-anderson** [comment]
Thanks for fixing this.
