### ISSUE TITLE
Missing return statement in \Robo\Common\ProgressIndicatorAwareTrait::getTotalExecutionTime

### ISSUE THREAD

**Issue by Sweetchuck** [consolidation/Robo#469]
https://github.com/consolidation/Robo/blob/1908cec67c6278d6d21535f14ca403cc860d4518/src/Common/ProgressIndicatorAwareTrait.php#L43

The last line of `\Robo\Common\ProgressIndicatorAwareTrait::getTotalExecutionTime()` should be:

```php
return $this->progressIndicator->getExecutionTime();
```
or
```php
return $this->progressIndicator ? $this->progressIndicator->getExecutionTime() : 0;
```

**Comment by greg-1-anderson** [comment]
Thanks.
