### ISSUE TITLE
ExecCommand::findProjectBin not working properly

### ISSUE THREAD

**Issue by Korikulum** [consolidation/Robo#474]
### Steps to reproduce
The `ExecCommand::findProjectBin` method stopped working properly since it was last altered (commit [9a53d59ffb5d9eaddb66c8d46286a0905366379f](https://github.com/consolidation/Robo/commit/9a53d59ffb5d9eaddb66c8d46286a0905366379f)).

I have both robo & codeception installed using composer:
```json
    "require": {
        ...
        "consolidation/robo": "~1.0@dev",
        ...
    },
    "require-dev": {
        ...
        "codeception/codeception": "2.1.*",
        ...
    },
```
& I have the following robo task:
```php
    public function test()
    {
        $suite = $this->ask('Which suite do you want to run?');

        $this->taskCodecept()
            ->suite($suite)
            ->run();
    }
```

I run the task with `bin/robo test` or `vendor/bin/robo test` (both of which are symlinks to `vendor/consolidation/robo/robo`).

### Expected behavior
Before the method was altered, the codeception installation would be found & the test would be run normally.

### Actual behavior
I get the following error:
```
 [error]    in task Robo\Task\Testing\Codecept 

  Neither composer nor phar installation of Codeception found.
```

**Comment by greg-1-anderson** [comment]
My results:
```
$ composer require consolidation/robo:dev-master codeception/codeception
$ vi RoboFile.php # add 'test' function
$ robo test
?  Which suite do you want to run? anything
 [Testing\Codecept] Executing ./vendor/bin/codecept run anything

  [Codeception\Exception\ConfigurationException]  
  Configuration file could not be found.          
  Run `bootstrap` to initialize Codeception.      
```

Looks right to me.  Are you using the latest version of Robo?

**Comment by Korikulum** [comment]
@greg-1-anderson Yes, I'm using the latest version of robo. I followed your instructions & got the same error as before. What exactly is `robo` in `robo test` in your example? I used `vendor/bin/robo test` to run robo.

**Comment by greg-1-anderson** [comment]
I have `./vendor/bin/robo` in my `$PATH`, so `robo` is just the `robo` from `vendor/bin`.

**Comment by greg-1-anderson** [comment]
```
$ which robo
./vendor/bin/robo
```
Don't know how to move forward here until we know what's different about your system that causes the error. Maybe write a short bash script or maybe repo that demonstrates the problem?

**Comment by Korikulum** [comment]
@greg-1-anderson I've done some testing & the only way I was able to get this to work as you described was by installing Codeception globally:
```
sudo curl -LsS http://codeception.com/codecept.phar -o /usr/local/bin/codecept
sudo chmod a+x /usr/local/bin/codecept
```
Are you sure that you don't have it installed globally as well?

**Comment by greg-1-anderson** [comment]
Ah, yes, I do have `./vendor/bin` in my $PATH. I'll take that out, and try again to reproduce this.

**Comment by greg-1-anderson** [comment]
Try again in latest master (c.f. https://github.com/consolidation/Robo/commit/39c1c24482fbcbc2d7a57620f64af6120dd3fe1e)

**Comment by Korikulum** [comment]
@greg-1-anderson Yep, I can confirm it works now, tnx.
