### ISSUE TITLE
http://robo.li/robo.phar returns 404

### ISSUE THREAD

**Issue by fousjiri** [consolidation/Robo#478]
The latest version of robo at http://robo.li/robo.phar is not available.

**Comment by herloct** [comment]
+1 to this.

For now, i'm using `releases` page.
```
https://github.com/consolidation/Robo/releases/download/1.0.0-RC3/robo.phar
```

**Comment by javigomez** [comment]
possible solutions for the robo.li site to always download the latest .phar http://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo

**Comment by DavertMik** [comment]
yep, we had a bug in release script. Fixed by now, and should not happen again
