### ISSUE TITLE
Documentation site not formatting well since last update

### ISSUE THREAD

**Issue by javigomez** [consolidation/Robo#481]
Hi, I noticed that the new line at https://github.com/consolidation/Robo/blame/master/docs/extending.md#L5 is not fitting in the documentation html rendered page. Note in the following image that the line is wider than the screen width:

<img width="1270" alt="extending" src="https://cloud.githubusercontent.com/assets/1375475/19906700/1f357d38-a07c-11e6-9290-58b83e1c6ab9.png">

The lines continues creating a horizontal scroll ignoring the screen width.

**Comment by greg-1-anderson** [comment]
The word loadTasks was supposed to be surrounded by backticks, but instead, the first backtick was replaced by a single-quote character. This messed up the formatting for the rest of the line. Fixed in `master`.
