### ISSUE TITLE
Why the version 1.0.0 was released based on commit  fe15768?

### ISSUE THREAD

**Issue by Sweetchuck** [consolidation/Robo#488]
`git clone -o upstream https://github.com/consolidation/Robo.git
`

----

Commit in an orphan branch.
`git branch --contains=$(git rev-parse 1.0.0)`
> _empty list_

----

There is at least one branch which contains the previous release.
`git branch --contains=$(git rev-parse 1.0.0-RC3)`
> `* master`

----

New commits.
`git log --pretty=format:'' 1.0.0..HEAD | wc -l`
> `33`

----

`git log --pretty=%cd --date=relative -1 1.0.0`
> 4 weeks ago

**Comment by DavertMik** [comment]
```
➜  Robo git:(master) gl
Already up-to-date.
```

**Comment by DavertMik** [comment]
Ok, I see, looks tag was accidentally put on the wrong branch

**Comment by DavertMik** [comment]
1.0.1 to fix that

**Comment by Sweetchuck** [comment]
:+1: Thank you :-)
