### ISSUE TITLE
Robo\Task\BaseTask and Robo\Common\TaskIO define the same property ($config)

### ISSUE THREAD

**Issue by useinoff** [consolidation/Robo#494]
Hello! 

our TC try to:
"bin/codecept run --group p* acceptance"

and then: 
ERROR: Robo\Task\BaseTask and Robo\Common\TaskIO define the same property ($config) in the composition of Codeception\Task\TestsSplitter. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed 

I think it's something like this - https://github.com/consolidation/Robo/issues/419 ?

**Comment by gdscei** [comment]
I hope this is fixed ASAP, can't use robo/codecept combo atm because of this error.

**Comment by greg-1-anderson** [comment]
I'm guessing that Codeception brings in both BaseTask and TaskIO, which is not necessary, since BaseTask uses TaskIO.  This is probably a 1.x-related change. Bring this to the Codeception issue queue, maybe?

**Comment by gdscei** [comment]
Apologies Greg, this is indeed Codeception related, I assumed too quickly it had to do with Robo.

**Comment by rodrigoaguilera** [comment]
Can you close the issue? It pollutes the search results
