### ISSUE TITLE
Help needed: migration from 1.0 beta to 1.x final

### ISSUE THREAD

**Issue by borgogelli** [consolidation/Robo#501]
Robo is growing very fast and in few month there have been many architectural changes. With the 1.0 beta we used the following code to init our loadTasks trait. And all worked fine.

```
$container = Robo\Config::getContainer();
$container->addServiceProvider(My\Robo\Task\loadTasks::getMyServices());

class RoboFile extends \Robo\Tasks {

   use My\Trait;

  // ...
}
```

and

```
trait My\Trait {
	
  use My\Robo\Task\loadTask;

  // ...
}
```

and

```
trait loadTasks
{

    public static function getMyServices()
    {
        return new SimpleServiceProvider(
            [
                'taskService' => Service::class,               
            ]
            );
    }

    /**
     * @return \My\Task\ServiceTask
     */
    protected function taskService($service_name)
    {
     return $this->task(__FUNCTION__, $service_name);  
    }
}
```
With the 1.x final release the previous solution is not working anymore.
So I try to switch from
`$container = Robo\Config::getContainer();`
to
`$container = Robo\Robo::getContainer();`
But I get
`Fatal error: Uncaught exception 'RuntimeException' with message 'container is not initialized yet. Robo\Robo::setContainer() must be called with a real container.'`

How can we migrate the above code ? 
I have read docs on robo's site, navigate all the github repo, searched in the issues list....all without success.
Any advices ? 
Thank you in advance.

**Comment by greg-1-anderson** [comment]
What are you trying to do?  Make a Robo extension with more tasks?  That is described in [Extending Robo](http://robo.li/extending/). There is a [working example PR for robo-drush here](https://github.com/boedah/robo-drush/pull/3).

**Comment by borgogelli** [comment]
Yes Greg, we have a Robo extension with more custom tasks.
Here is what I have done in the meantime.

First, I have removed the SimpleServiceProvider:

```
trait loadTasks
{

    /**
     * @return \My\Task\ServiceTask
     */
    protected function taskService($service_name)
    {
          return $this->task(WinService::class, $service_name);  
    }
}
```
Then I have removed all the container references, deleting the following two statements:
```
$container = Robo\Config::getContainer();
$container->addServiceProvider(My\Robo\Task\loadTasks::getMyServices());
```
Now everything magically works even if I did not understand why.
In fact with the version 1.0 beta I had to use addServiceProvider() method and the SimpleServiceProvider class. Now, with the last release, both seem unnecessary.

**Comment by borgogelli** [comment]
Issue is closed, but some explanations would be appreciable. 
Thank you in advance.

**Comment by greg-1-anderson** [comment]
SimpleServiceProvider is no longer necessary. Robo 1.x is now very similar to Robo 0.x in terms of requirements for extension writers.
