### ISSUE TITLE
Default boolean value in command options is cast to null

### ISSUE THREAD

**Issue by borgogelli** [consolidation/Robo#505]
I'm using Robo 1.0.5

In the following example, when I call
 `robo do:something` 
the value of the `option1` parameter is false. I expected it to be true because its default value is true.

```
public function doSomething(array $opts = ['option1' => true]){
    // 
    // print_r($opts);
    //
    // Array
    // (
    //    [option1] =>
    //    [help] =>
    //    [quiet] =>
    //    [verbose] =>
    //    [version] =>
    //    [ansi] =>
    //    [no-ansi] =>
    //    [no-interaction] =>
    //    [simulate] =>
    //    [progress-delay] => 2
//  )
}
```

While if I use an integer value as default for `option1`, then all works fine:

```
public function doSomething(array $opts = ['option1' => 1]){
    // 
    // print_r($opts);
    //
    // Array
    // (
    //    [option1] => 1
    // ....
    // ...
}
```

**Comment by thomscode** [comment]
According to [documentation](http://robo.li/getting-started/#commands):

> The default value for options must be one of:
> * The boolean value false, which indicates that the option takes no value.
> * A **string** containing the default value for options that may be provided a value, but are not required to.
> * `NULL` for options that may be provided an optional value, but that have no default when a value is not provided.
> * The special value `InputOption::VALUE_REQUIRED`, which indicates that the user must provide a value for the option whenever it is used.
> * An empty array, which indicates that the option may appear multiple times on the command line.
>
> No other values should be used for the default value. For example, `$options = ['a' => 1]` is **incorrect**; instead, use `$options = ['a' => '1']`. Similarly, `$options = ['a' => true]` is unsupported, or at least not useful, as this would indicate that the value of `--a` was always `true`, whether or not it appeared on the command line.

I'm not sure of your exact use case, and theoretically it should work; but according to the documentation this isn't supported.

**Comment by greg-1-anderson** [comment]
If `option1` defaults to `false`, then you can make it true via `--option1`.

If `option1` defaults to `true`, how do you expect to set it to false? Via `--option1=0`? In that case, use an integer instead of a boolean. As mentioned above, `true` is not supported as an option's default value.

Perhaps the code should throw an exception if someone tries this. PRs welcome (although any such PR should be in the https://github.com/consolidation/annotated-command project).
