### ISSUE TITLE
collectionBuilder::addCode()'s signature doesn't allow you to name a task...?

### ISSUE THREAD

**Issue by bwood** [consolidation/Robo#540]
### Expected behavior
Per [the named tasks documentation](https://github.com/consolidation/Robo/blob/master/docs/collections.md#named-tasks) I expect to be able to name a task by providing a second argument to `collectionBuilder::addCode()`

To make this work do we need this modification:
```diff
diff --git a/src/Collection/CollectionBuilder.php b/src/Collection/CollectionBuilder.php
index 191d814..4fc9946 100644
--- a/src/Collection/CollectionBuilder.php
+++ b/src/Collection/CollectionBuilder.php
@@ -139,9 +139,9 @@ class CollectionBuilder extends BaseTask implements NestedCollectionInterface, W
         return $this;
     }

-    public function addCode(callable $code)
+    public function addCode(callable $code, $name)
     {
-        $this->getCollection()->addCode($code);
+        $this->getCollection()->addCode($code, $name);
         return $this;
     }
```
...or have I completely missed something?

**Comment by greg-1-anderson** [comment]
Looks like that wrapper method is just missing a parameter. PRs welcome.

**Comment by bwood** [comment]
Hopefully this is better.  Let me know if you see anything else.
