### ISSUE TITLE
Hook for failure on tasks?

### ISSUE THREAD

**Issue by BrunoRB** [consolidation/Robo#543]
I have multiple tasks running at once and the whole process aborts at the first failure of any of those (`stopOnFail()`), something like:

    public function all() {
		$this->stopOnFail(); // abort when some task fail
		$this->preSetup();
		$this->lintES();
		$this->codecept();
		...
	}

I need to execute some piece of code when a task fails, like:

         // this method runs when stopOnFail(true) and some task failed
        public function runOnFailure() {
            // stuff.
        }

How can I achieve this?

**Comment by greg-1-anderson** [comment]
You need to stop using `stopOnFail()` and start using [collections](http://robo.li/collections/).
