### ISSUE TITLE
Pass-Through Arguments not working

### ISSUE THREAD

**Issue by jalogut** [consolidation/Robo#550]
### Steps to reproduce
Trying to test exactly what stays in documentation
http://robo.li/getting-started/?#commands

```
<?php
    function ls($args)
    {
        $this->taskExec('ls')->args($args)->run();
    }
?>
```

then running following command:
```
robo ls -- Robo -c --all
```
### Expected behavior
```
[Robo\Task\ExecTask] running ls Robo -c --all
```

### Actual behavior
```
 [Symfony\Component\Console\Exception\RuntimeException]
 Too many arguments, expected arguments "command" "args".
```
### System Configuration
Mac OS El Capitan 10.11.6 && php 7.0.15

### Other information
Defining `$args` parameter as array seems to work but not exactly as expected:

```
<?php
    function ls(array $args) 
    {
        var_dump($args);
    }
?>
```

Previous example works and `$args` will contain and array as follows:

```
array(3) {
  [0] =>
  string(4) "Robo"
  [1] =>
  string(2) "-c"
  [2] =>
  string(5) "--all"
}
```

However, if I set an option before and do not provide it in the command line the result is not as expected:

```
<?php
    function ls($opts = ['option1' => 'test'], array $args)
    {
        var_dump($opts);
        var_dump($args);
    }
?>
```

running:

```
robo ls -- Robo -c --all
```

#### Expected result
```
array(1) {
  ['option1'] => string(4) "test"
}
array(3) {
  [0] =>
  string(4) "Robo"
  [1] =>
  string(2) "-c"
  [2] =>
  string(5) "--all"
}
```

#### Actual behaviour
```
string(4) "Robo"
array(2) {
  [0] =>
  string(2) "-c"
  [1] =>
  string(5) "--all"
}
```

**Comment by greg-1-anderson** [comment]
This is a documentation bug. The first example of multiple args is correct:
```
function hello(array $world)
```
The second example, with `ls`, is incorrect; it is missing the `array` marker that indicates that the parameter should take the rest of the arguments. Without the `array`, each parameter takes but a single argument.

**Comment by jalogut** [comment]
Hi @greg-1-anderson 

Thanks for your quick answer, I also thought that this was a documentation bug. 
Regarding the other issue at the end of my comment. Should I open a new issue for that? I would expect that everything after `--` goes into the latest param. That way, it would be possible to have `optional options` together with `Pass-Through Arguments`

**Comment by greg-1-anderson** [comment]
@jalogut See my answer at https://github.com/consolidation/Robo/issues/551#issuecomment-288761061
