### ISSUE TITLE
Optional params + Pass-through Arguments

### ISSUE THREAD

**Issue by jalogut** [consolidation/Robo#551]
### Steps to reproduce
```
<?php
    function testCommand($param = 'foo', array $args)
    {
        var_dump($param);
        var_dump($args);
    }
?>
```

execute:
```
robo test:command -- Robo -c --all
```

### Expected behavior
I would expect that everything after `--` is passed to the latest `$args` parameter.

```
string(3) "foo" 

array(3) {
  [0] =>
  string(4) "Robo"
  [1] =>
  string(2) "-c"
  [2] =>
  string(5) "--all"
}
```

### Actual behavior
```
string(4) "Robo"

array(2) {
  [0] =>
  string(2) "-c"
  [1] =>
  string(5) "--all"
}
```

### System Configuration
MAC OS El Capitan 10.6.11 && PHP 7.0.15

**Comment by greg-1-anderson** [comment]
The meaning of `--` is slightly different than what you expect. `--` simply means that none of the elements in `$argv` that follow should be interpreted as options: all are arguments. Once Robo categorizes `$argv` into arguments and options, it merely takes the first N arguments and passes them to the first N parameters of the command function that are single-argument variables. The rest go into the `array` arguments.

It is possible to add your own custom heuristic in a hook function to alter how arguments are collated.  See https://github.com/pantheon-systems/terminus/pull/1454 for a discussion.

**Comment by jalogut** [comment]
Ok, thanks for the clarification. That means that is not possible to have a command that expects an **optional** `argument/option` and `pass-Through Arguments` right. So `pass-Through Arguments` are meant to be used in commands that only expect this `$args` or also other **required** `argument/options`. To summarise:

This Works:

```
public function command($arg, array $args)
public function command($option = ['foo'], array $args)
public function command($arg, $option = ['foo'], array $args)
```

This does not work:

```
public function command($arg = 'foo', array $args)
public function command($option = ['foo' => 'foo'], array $args)
```

Thanks for your answer, I just wanted to be sure that this was not a bug and understand exactly how it works.

**Comment by greg-1-anderson** [comment]
`$options` always go at the very end, after the variable arguments.

This works fine:
```
public function command($arg = 'foo', array $args, $options = ['foo' => false]);
```
In this case, `$arg` will be 'foo' iff the command is called with no arguments whatsoever. Otherwise, it will contain the value of the first argument.  `$args` will contain the second through Nth arguments.
