### ISSUE TITLE
Robo command times out when called via Composer event.

### ISSUE THREAD

**Issue by FatherShawn** [consolidation/Robo#565]
### Steps to reproduce
I defined a call to robo as a Composer script, and invoke robo command in post-install:
```
"scripts": {
        "drupal-scaffold": "DrupalComposer\\DrupalScaffold\\Plugin::scaffold",
        "robo": "robo --ansi --load-from $(pwd)/scripts/robo",
        "pre-install-cmd": [
            "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
        ],
        "pre-update-cmd": [
            "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
        ],
        "post-install-cmd": [
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles",,
            "composer robo setup:prerequisites",
            "composer robo setup:docker",
            "composer robo setup:dns"
        ],
        "post-update-cmd": [
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles",
            "composer robo setup:prerequisites",
            "composer robo setup:docker",
            "composer robo setup:dns"
        ]
    },
```

The problem occurs in the middle command:
```
  /**
   * Robo Command that dispatches docker setup tasks by OS.
   *
   * @ingroup setup
   */
  public function setupDocker() {
    switch (php_uname('s')) {
      case 'Darwin':
        $home = getenv('HOME');
        if (!file_exists("$home/.docker/machine/machines/dp-docker")) {
          $this->setupDockerMac();
        }
        else {
          $this->io()
            ->success("All set! DP Docker Machine config detected at $home/.docker/machine/machines/dp-docker");
        }
        break;

      default:
        $this->io()
          ->error("Unable to determine your operating system.  Manual installation will be required.");
    }
  }

  /**
   * Download Linux kernel and create the xhyvee based VM for Mac containers.
   */
  public function setupDockerMac() {
    $this->io()->title('Build the dp-docker machine');
    $collection = $this->collectionBuilder();
    $collection->addTask(
      $this->taskExec('docker-machine create -d xhyve --xhyve-memory-size 2048 dp-docker')
    )->rollback(
      $this->taskExec('docker-machine rm dp-docker')
    );
    $result = $collection->run();
    if ($result instanceof Result && $result->wasSuccessful()) {
      $this->io()->success("Docker machine created.");
    }
    else {
      $this->io()
        ->error("Something went wrong.  Changes have been rolled back.");
    }
  }
```

### Expected behavior
Each robo command executes properly when run outside of Composer on its own.  Expected behavior is that it would do so here as well.

### Actual behavior
setup:docker outputs its success message and then stalls until the 300 second execution limit is reached and it times out.  This only happens when run via Composer.

### System Configuration
PHP 5.6.30 (cli) (built: Mar 11 2017 09:56:27)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

macOS Sierra 10.12.3

**Comment by greg-1-anderson** [comment]
Try running with `--no-interaction`

**Comment by FatherShawn** [comment]
Thanks for the quick support @greg-1-anderson !  That made no difference, but I had no user questions.  I also tried with --quiet.  I guess my next step is run it under xdebug and see if I can see where it hangs.

**Comment by greg-1-anderson** [comment]
Also, I noticed that you are using `exec` to launch Docker. Have you tried [taskDockerRun](https://github.com/consolidation/Robo/blob/master/src/Task/Docker/loadTasks.php#L11) et. al and see if they work better?

There are no functional tests for these tasks, so I can't guarentee that they're working right now, but it'd be good to know if they were or were not.

**Comment by FatherShawn** [comment]
I am using `exec` to tell `docker-machine` to create a new machine to host docker containers.  Once that exists, I do use some of the docker taskDockerRemove and taskDockerRun in other methods. But this maybe something in Composer?  I get all the way to the `exit()` call in `vendor/consolidation/robo/robo` with `$statuscode == 0` 

My "holy grail" was for my devs to be able to `composer install` and everything get setup, but two commands is not the end of the world!
