### ISSUE TITLE
Question: how to output to console from a BaseTask child ?

### ISSUE THREAD

**Issue by borgogelli** [consolidation/Robo#567]
With Robo 1.06, I have extend the BaseTask and included the IO trait.
But the custom task I can't write output to console with the methods say() , confirm() and doAsk().
Where am I wrong ?
Regards.

**Comment by greg-1-anderson** [comment]
Tasks are only supposed to produce output via the logger. Place your confirm / ask code in a command, and use tasks to implement operations that run based on the information provided to them via their parameters.
