### ISSUE TITLE
Question: artisan commands

### ISSUE THREAD

**Issue by amenk** [consolidation/Robo#571]
In the documentation you mention an artisan command.

http://robo.li/tasks/Base/#symfonycommand

This is only working if robo is composer required' to the current laravel project, right?

Is there a way to use it with a monolithic (i)robo.phar ?

**Comment by greg-1-anderson** [comment]
Yes, that example assumes that Robo is included in the project that contains the commands you'd like to run. Use `taskExec` for running commands in a separate application.

It is indeed possible to create your own monolithic robo.phar (usually renamed to something else to indicate its purpose); see [Robo as a Framework](http://robo.li/framework) for more information.
