### ISSUE TITLE
calling stopOnFail(TRUE) prevents result data from being accessed 

### ISSUE THREAD

**Issue by grasmash** [consolidation/Robo#574]
The value returned by taskExec() changes dramatically depending on whether stopOnFail(TRUE) is used, and whether the executed task fails. This is very confusing:
https://github.com/consolidation/Robo/blob/master/src/Task/CommandStack.php#L107

The result is that output data becomes inaccessible if stopOnFail(TRUE) is used, regardless of whether the task fails.

**Comment by greg-1-anderson** [comment]
The specific problem is that the [intermediate $result is discarded](https://github.com/consolidation/Robo/blob/master/src/Task/CommandStack.php#L114) in the `stopOnFail()` case. Each of these should be merged together.
