### ISSUE TITLE
Docker tasks print TaskInfo twice

### ISSUE THREAD

**Issue by kitgrose** [consolidation/Robo#576]
### Steps to reproduce
Add the following task to your `RoboFile` and run it (where `container_id` is the name of a valid Linux Docker container).

```php
public function test() {
    $this->taskDockerExec('container_id')->exec('ls')->run();
}
```

### Expected behavior
The output should contain the following text once before the output of `ls`:

```
 [Docker\Exec] Running docker exec  container_id ls
```

### Actual behavior
The output contains that line twice:

```
 [Docker\Exec] Running docker exec  container_id ls
 [Docker\Exec] Running docker exec  container_id ls
```

This is apparently caused by line 23 of `src/Task/Docker/Base.php`, which prints the task info. The task info is already being printed as part of `ExecTrait` as part of `printAction()` (called by `execute()`).

As far as I can tell it seems like the best solution is simply to remove line 23 of `src/Task/Docker/Base.php` and rely on `ExecTrait` to print the task info (but I'm not yet familiar enough with the Robo codebase to be confident about that).

### System Configuration
macOS Sierra v10.12.4. PHP 5.6.8.

**Comment by greg-1-anderson** [comment]
Sounds right to me. If the suggested fix clears up the problem for you, a PR would be welcome.
