### ISSUE TITLE
How does the exclude of subfolders work in copyDir-Task?

### ISSUE THREAD

**Issue by thomasgrass** [consolidation/Robo#582]
Hi,
i know that it is possible to exclude folders and files from the taskCopyDir doing it like:

`$this->taskCopyDir(['./' => sprintf('%s', $deployFolderName)])
                ->exclude(['.idea', 'node_modules'])
                ->run();`

But what if i want to exclude subfolders (but not the parent folder)? This command won't work - the subfolders will be copied anyway:

`$this->taskCopyDir(['./'` => sprintf('%s', $deployFolderName)])
                ->exclude(['parent/the_sub_folder'])
                ->run();`

Thomas

**Comment by greg-1-anderson** [comment]
As currently implemented, the `exclude` method of `taskCopyDir` only accepts names of files immediately inside the source directory. This can apply recursively, so `exclude(['foo'])` will exclude `foo` and `bar/foo`.  However, `exclude(['bar/foo])` does not work at all in the current implementation.

A PR would be welcome here, but it would also have to consider how to reconcile the current behavior, where excluding `foo` excludes **any** foo anywhere in the copy tree, with the proposed new behavior to only exclude items named `foo` that are inside a `bar` folder.

**Comment by alexdesignworks** [comment]
@greg-1-anderson 
I'm not sure why this is closed as it is an active issue - specifying the full path to excluded file/dir should work out of the box.

**Comment by greg-1-anderson** [comment]
`taskCopyDir` behaves as documented. A pull request would be welcome, but we do not necessarily hold open feature request issues.

**Comment by greg-1-anderson** [comment]
As an alternative, you might want to try taskRsync, which has more options.

**Comment by thomasgrass** [comment]
Thank you so much for your support! The exclude of subfolders works like a charme!
