### ISSUE TITLE
DOCS: How to make all tasks stop printing their output and only print sayOkay()

### ISSUE THREAD

**Issue by alexdesignworks** [consolidation/Robo#592]
I've been trying to suppress command output from `Exec`  task so that only explicitly defined output by functions like `sayOkay()` (and others) is shown. `--quiet` flag suppresses all commands, and `-v|vv|vvv` simply has no effect.

If there is a special flag or if `Exec` has some method to suppress command output, can this information be added somewhere in the docs (or at least here for reference). 

Thanks

**Comment by greg-1-anderson** [comment]
This is not supported in Robo 1.x unless you use [Robo as a Framework](http://robo.li/framework/) and insert your own output handling classes.

However, most of the `say`-related functions output to stdout, and log messages output to stderr. You could try running your command with `2>/dev/null`, and see if that works well enough for your purposes.
