### ISSUE TITLE
GitStack push with tag

### ISSUE THREAD

**Issue by llaville** [consolidation/Robo#599]
### Steps to reproduce
I wanted to push list of modifications with a tag to a remote repo

```php
        $tag = '0.1.0';
        $message = 'release 0.1.0 with ... ';

        $this->taskGitStack()
            ->checkout('master')
            ->merge('develop')
            ->tag($tag, $message)
            ->push('origin','master')
            ->run()
        ;
```

### Expected behavior
tag available on remote repository

### Actual behavior
Only commits are pushed to the remote branch, but not the tag

### System Configuration
Linux and PHP 5.6

**Comment by greg-1-anderson** [comment]
Try `->push('origin', $tag)`

**Comment by llaville** [comment]
I confirm this is the right action to do !
BTW, I've found other issues with GitStack

Cannot add multiple action like 

```
        $this->taskGitStack()
            ->add('composer.json')
            ->commit('my frist comment')
            ->add('composer.lock')
            ->commit('my second comment)
            ->tag($tag, $message)
            ->push('origin', $tag)
            ->run()
        ;
```

compose.lock is not added / commited and push not apply too

Your point of view ?

**Comment by greg-1-anderson** [comment]
Please open new issues for new problems. Run with --simulate to see what GitStack is doing.

**Comment by llaville** [comment]
Of course !
