### ISSUE TITLE
IO interactions not working when using composer script

### ISSUE THREAD

**Issue by obstschale** [consolidation/Robo#621]
### Steps to reproduce
What did you do?

#### 1. Install Robo
```sh
$ composer require --dev consolidation/robo
Using version ^1.1 for consolidation/robo
...
```

#### 2. Add script to composer.json
```json
"scripts": {
    "robo": "robo --ansi"
}
```

#### 3. Add run command to RoboFile
```php
class RoboFile extends \Robo\Tasks
{
    public function run()
    {
        $this->io()->title("Sample Title");
        $name = $this->askDefault("What is your name?", "John");
        $this->say("Hello {$name}");
    }
}
```

#### 4. Run Robo
```sh
$ composer robo run
```

### Expected behavior
I expect to see the title output "Sample Title" and Robo should ask me for my name and greets me, with my name or the default name.

### Actual behavior
Robo executes properly, but IO interactions are not performed. So either `$this->ask()`, `$this->askDefault()` neither `$this->confirm()` work if I run robo with `composer robo run`.

If I run Robo directly (`./vendor/bin/robo run`) the question and confirmation works.

### System Configuration
macOS: 10.11.6
Robo: 1.1
PHP: 7.1.8

**Comment by greg-1-anderson** [comment]
This is a limitation of Composer, which runs all scripts in non-interactive mode.

See: https://github.com/composer/composer/issues/5856

**Comment by obstschale** [comment]
I didn't know that. Thx @greg-1-anderson for pointing this out.
