### ISSUE TITLE
Extinguish the output of a task

### ISSUE THREAD

**Issue by salarmehr** [consolidation/Robo#629]
Thanks for this awesome tool. I s there any option to make a task silent or set the verbosity level pleaes?

**Comment by greg-1-anderson** [comment]
Try `--quiet` if you want absolute silence. If you are writing your own RoboFile commands, try fiddling with the methods of `VerbosityThresholdTrait`.

For full control over the output, you must [write your own Robo-based application](https://robo.li/framework).  RoboFile scripts do not support manipulating the dependency injection container.

**Comment by damienflament** [comment]
The `--quiet` is not totally silent.

Using the command below:

```php
public function validate(): TaskInterface
{
    return $this->taskComposerValidate();
}
```

Robo is not totally silent when running this command:

```console
$ robo validate --quiet

  [Seld\JsonLint\ParsingException]
  "./composer.json" does not contain valid JSON
  Parse error on line 1:
  {  OOPS  "name": "simo
  --^
  Expected one of: 'STRING', '}'
```

**Comment by greg-1-anderson** [comment]
Perhaps taskExec is not correctly handling the stderr of exec'ed tools with `--quiet`

**Comment by damienflament** [comment]
For _taskExec_, the [printOutput()](https://github.com/consolidation/Robo/blob/ed9cdb84dfeaaddefc45f3f00c1709d52582cd20/src/Common/ExecTrait.php#L254) and [silent()](https://github.com/consolidation/Robo/blob/ed9cdb84dfeaaddefc45f3f00c1709d52582cd20/src/Common/ExecTrait.php#L223) methods from [ExecTrait](https://github.com/consolidation/Robo/blob/ed9cdb84dfeaaddefc45f3f00c1709d52582cd20/src/Common/ExecTrait.php) do the job.

**Comment by alexdesignworks** [comment]
For information and future google searches.

There are different *kinds* of verbosity.

Consider example:

```php
$result = $this->taskExecStack()
    ->exec('which git')
    ->run();
```
that would produce:

```
 [ExecStack] which git              <-- Task info
 [ExecStack] Running which git      <-- Task progress line 1
/usr/bin/git                        <-- Task's command output
 [ExecStack] Done in 0.008s         <-- Task progress line 2
```

----

If you do not want to ouput either task info (`[ExecStack] which git`), task progress(`Running which git`) or the output of the tasks's command (`/usr/bin/git`):
```
$result = $this->taskExecStack()
    ->setVerbosityThreshold(VerbosityThresholdInterface::VERBOSITY_DEBUG)
    ->exec('which git')
    ->run();
```
output
```
(nothing)
```

Use this if you wrap Robo's commands with your own commands, which may already have verbose logging.

Really important to use `VerbosityThresholdInterface::VERBOSITY_DEBUG` rather then `OutputInterface::VERBOSITY_DEBUG`.
The `VERBOSITY_DEBUG` can be set to the required level, of course. In this example, calling the Robo command with `-vvv` (verbosity level == debug) would actually print task info, task progress and the output of the task command itself, so there is still a way to access the output, if required.

----

If you want to output task info and task progress, but not the output of the task's command:
```
$result = $this->taskExecStack()
    ->printOutput(false)
    ->exec('which git')
    ->run();
```
output
```
 [ExecStack] which git              <-- Task info
 [ExecStack] Running which git      <-- Task progress line 1
 [ExecStack] Done in 0.008s         <-- Task progress line 2
```

----

If you want to output only task info, but no task progress or the output of the task's command:
```
$result = $this->taskExecStack()
    ->silent(true)
    ->exec('which git')
    ->run();
```
output

```
 [ExecStack] which git              <-- Task info
```

**Comment by salarmehr** [comment]
Sorry, I'm not sure what is the best practice in using this option. My first robo task is a task to compile less files with its native node compilter as follow:

```
<?php

use Symfony\Component\Finder\Finder;

class RoboFile extends \Robo\Tasks
{
  function less()
  {
    $lessDirs = [
      __DIR__ . '/public/css',
      __DIR__ . '/public/vendor',
    ];

    $sources = (new Finder())->in($lessDirs)->name('*.less');
    $lessCmd = '';

    foreach ($sources as $source) {
      $target = "{$source->getPath()}/{$source->getBasename('.less')}.css";
      $lessCmd .= "lessc '{$source->getRealPath()}' '$target'" . PHP_EOL;
    }

    $this->_exec($lessCmd);
    $_base = realpath(__DIR__ . "/public/css/all.css");
    $this->_exec("cleancss -o {$_base} {$_base}");
  }
}
```

Have I implemented this task according to Robo style correctly? 
It works.

I need to keep the Robo task execution output and strip the less output only.

Thanks.

**Comment by greg-1-anderson** [comment]
You are not obligated to use `$this->_exec()` or any of the Robo flavors of `exec` if they are not behaving they way you wish. One good & really simple way to avoid printing the output of a sub-program is to just use the php `exec` function.

**Comment by koppieesq** [comment]
This thread was super helpful, someone ought to put it in the documentation.  ;-) To add one more:

Here's how you get _just_ the of your command, with no commentary from Robo:
```
      ->silent(TRUE)
      ->printOutput(TRUE)
```
