### ISSUE TITLE
Adding {name} as a substitution value overrides Task name in print logs

### ISSUE THREAD

**Issue by thomscode** [consolidation/Robo#634]
I'm not sure if this is the right repository to for this issue or if this should be in the logging repo. My guess is here as the context is handled in `Robo\Common\TaskIO`.

### Steps to reproduce
* Create a new task
* Create a message that uses `{}` substitution with `{name}` as a substituted string
* Print Task Info, Error, and Success with the above message

### Expected behavior
No substitutions can override task name in log

### Actual behavior
Using the `name` parameter for substitution in the `context` array overrides both `{name}` entries and the task's name in the log output.

### System Configuration
* macOS 10.12.6
* PHP 5.6.31
* Robo 1.1.3

If this is working as expected that is fine, I just wanted to make sure this either was the desired behavior or was in the queue to get fixed.

**Comment by thomscode** [comment]
Example `run()` method:

```php
    public function run()
    {
        $this->printTaskInfo("Overriding name: {name}", ['name' => "TEST"]);
        $this->printTaskError("Overriding name: {name}", ['name' => "TEST"]);
        $this->printTaskSuccess("Overriding name: {name}", ['name' => "TEST"]);
    }
```

Actual output:

```
 [TEST] Overriding name: TEST
 [TEST]  Overriding name: TEST 
 [TEST] Overriding name: TEST
```

Expected output:

```
 [thomscode\Test\Example] Overriding name: TEST
 [thomscode\Test\Example]  Overriding name: TEST 
 [thomscode\Test\Example] Overriding name: TEST
```

**Comment by greg-1-anderson** [comment]
Yes, the task name is `{name}` in the context array. This was probably not the best choice. We should probably change this in the next major release.
