### ISSUE TITLE
https download for latest robo.phar

### ISSUE THREAD

**Issue by pingers** [consolidation/Robo#640]
### Steps to reproduce
Visited http://robo.li and attempted to use https to download https://robo.li/robo.phar

### Expected behavior
robo.phar download

### Actual behavior
No TLS certificate on https://robo.li

I know it's pretty low priority, but would be good to get a secure download link for the phar... https://letsencrypt.org/ is better than no cert.
Cheers!

**Comment by pingers** [comment]
I guess because it's github pages, you can't easily use a non *.github.io domain. I.e. github pages supposer https https://github.com/blog/2186-https-for-github-pages. You'd need to configure a CDN in front of it to do the re-writing. Boo. Can probably close this issue and I'll just keep manually updating from the github releases page using https.

**Comment by greg-1-anderson** [comment]
@DavertMik set this up; it's up to him if he'd like to do something else.

**Comment by Rarst** [comment]
This works fine now (and for trivia GitHub pages support Let's Encrypt now).

**Comment by pingers** [comment]
Tested - fixed 👍
