### ISSUE TITLE
Documentation about extending not up-to-date 

### ISSUE THREAD

**Issue by legovaer** [consolidation/Robo#643]
### Steps to reproduce
I tried to use the code snippet in https://github.com/consolidation/Robo/blob/master/docs/extending.md#create-the-loadtasksphp-trait

### Expected behavior
I would be able to use the `SimpleServiceProvider`

### Actual behavior
The `SimpleServiceProvider` is nowhere to be found

### System Configuration
Using latest version of Robo.

**Comment by greg-1-anderson** [comment]
Are you including your new provider in your RoboFile via a `use` statement as described in the section [including additional tasks](https://github.com/consolidation/Robo/blob/master/docs/extending.md#including-additional-tasks)?

The documentation should be updated here in one respect, though, as we are now recommending that the `loadTasks` trait be called simply `Tasks`. We're not making this change in Robo core at the moment to preserve backwards-compatibility, but 'loadTasks' is not a PSR-2-compliant name (should start with an uppercase letter).

**Comment by legovaer** [comment]
Well, I'm currently developing a new extension and one of my dependencies is Robo:

```
  "require": {
    "php": ">=5.5.0",
    "consolidation/Robo": "~1"
  },
```

But I can't find the class `SimpleServiceProvider` anywhere in the Robo package.

**Comment by greg-1-anderson** [comment]
`SimpleServiceProvider` is no longer required. I have removed the vestigial `use` statement from the documentation.

I am also ambivalent about a plugin (e.g. a Robo task) requiring its parent application. I usually think this is better off omitted from the plugin's composer.json. For the time being, though, I have left this in the documentation.
