### ISSUE TITLE
Verbosity on taskFileSystemStack

### ISSUE THREAD

**Issue by FatherShawn** [consolidation/Robo#644]
### Steps to reproduce
I set the collection thus:
```php
$collection = $this->collectionBuilder();
    $collection->setVerbosityThreshold(VerbosityThresholdInterface::VERBOSITY_VERBOSE);
    if ($options['debug']) {
      $collection->setVerbosityThreshold(0);
    }
```

### Expected behavior
The progress output from `taskFileSystemStack` should be suppressed unless `$options['debug']` is true.

### Actual behavior
I get progress indicators.

### System Configuration
php 7.1 running in alpine linux

**Comment by greg-1-anderson** [comment]
If you only want to see progress output in debug mode, did you try `$collection->setVerbosityThreshold(VerbosityThresholdInterface::VERBOSITY_DEBUG);`?

**Comment by FatherShawn** [comment]
Thank you Greg for being so responsive!

I found that I needed to set the threshold on the underlying task stack:

```php
    // If $options['debug'] is set (TRUE) then lower the threshold to normal.
    // Otherwise keep it up at debug.
    $collection->setVerbosityThreshold($options['debug'] ? VerbosityThresholdInterface::VERBOSITY_NORMAL : VerbosityThresholdInterface::VERBOSITY_DEBUG);
    $taskFilesystemStack->setVerbosityThreshold($options['debug'] ? VerbosityThresholdInterface::VERBOSITY_NORMAL : VerbosityThresholdInterface::VERBOSITY_DEBUG);
    $collection->addTask($taskFilesystemStack);
```

I do still get progress from the collection, but that's not filling up the CI logs too much:
```
2017-11-03T17:43:43.624Zdeploy  0/10 [>---------------------------]   0%
  0/10 [>---------------------------]   0%
 15/15 [============================] 100%
 16/16 [============================] 100%
 17/17 [============================] 100%
 18/18 [============================] 100%
 19/19 [============================] 100%
 20/20 [============================] 100%
 21/21 [============================] 100%
 22/22 [============================] 100%
 23/23 [============================] 100%
 24/24 [============================] 100%
 25/25 [============================] 100%
 25/25 [============================] 100%
```

**Comment by greg-1-anderson** [comment]
I've been meaning to disable the progress indicator for non-interactive calls. Presumably CI scripts will always use non-interactive mode already to avoid holding up CI on unexpected prompts.

**Comment by greg-1-anderson** [comment]
Also, your use of `$options['debug']` in the example above seems redundant. I would expect `VerbosityThresholdInterface::VERBOSITY_DEBUG` would be sufficient there.

**Comment by FatherShawn** [comment]
`$options['debug']` flows from an `$options` parameter on the command, so that `robo command --debug` will trigger verbose output.

Thanks again for such an awesome tool!

**Comment by greg-1-anderson** [comment]
Using `VerbosityThresholdInterface::VERBOSITY_DEBUG` on its own should trigger verbose output only in debug mode.

**Comment by FatherShawn** [comment]
Oh of course (blush) I can just use `-vvv` when I want debug.

**Comment by greg-1-anderson** [comment]
Terminus and Drush both define `--debug`; I forget that Robo does not have that.
