### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by Naktibalda** [consolidation/Robo#648]
Some other projects support Symfony 4 already, but Robo pins some Symfony components down to 3.*.

Please implement support for Symfony 4.

**Comment by greg-1-anderson** [comment]
This will have to happen in consolidation/annotated_command & c. first.

Help appreciated.

**Comment by cmmata** [comment]
> This will have to happen in consolidation/annotated_command & c. first.
That means consolidation/log, consolidation/config, consolidation/annotated-command & consolidation/output-formatters? Any one more? I could try to take a look, I'm planning to upgrade my Symfony projects to v4 and would like to have Robo upgraded too.

**Comment by greg-1-anderson** [comment]
Here are our dependencies:
```
$ composer why symfony/console
codeception/base                    2.3.6       requires  symfony/console (>=2.7 <4.0)            
consolidation/annotated-command     2.8.1       requires  symfony/console (^2.8|~3)               
consolidation/log                   1.0.3       requires  symfony/console (~2.5|~3.0)             
consolidation/output-formatters     3.1.12      requires  symfony/console (^2.8|~3)               
consolidation/robo                  dev-master  requires  symfony/console (~2.8|~3.0)             
satooshi/php-coveralls              v1.0.2      requires  symfony/console (^2.1 || ^3.0 || ^4.0)  
stecman/symfony-console-completion  0.7.0       requires  symfony/console (~2.3 || ~3.0) 
```
There's a chance that there might be some other Symfony component dependencies that need upgrading outside of those projects that depend on symfony/console, but the above is a start.

`stecman/symfony-console-completion` is only a dev dependency, but we're going to need to do those too if we want to test. (We want to test. 😉  )

**Comment by greg-1-anderson** [comment]
Also, I had previously received a PR in consolidation/log to add Symfony 4 support, which required nothing more than altering the version constraints on the Symfony components in the composer.json file. I just tagged 1.0.4 including that change, so you can cross consolidation/log off of the list above.

**Comment by greg-1-anderson** [comment]
Doing output-formatters now.

**Comment by greg-1-anderson** [comment]
The consolidation/log PR wasn't valid. It is necessary to require `"satooshi/php-coveralls": "dev-master"`, as all of the stable releases use an old version of guzzle that pin to an old version of symfony/event-dispatcher. Re-doing that component.

**Comment by greg-1-anderson** [comment]
All righty, consolidation/log 1.0.4 was fine as a library, but I tagged 1.0.5 with a better test suite that proves that it is fine for Symfony 2, 3 and 4. Anyone who is trying to update a project for multiple versions of Symfony should look at https://github.com/consolidation/log/pull/5 for guidance.

Going to move on and do the same thing for consolidation/output-formatters next.

**Comment by greg-1-anderson** [comment]
I did consolidation/output-formatters in https://github.com/consolidation/output-formatters/pull/62. This is not merged yet, as there are some failing tests in the Appveyor build. The failed tests are asserting as failed even though the output appears the same in the diff. The difference no doubt lies in the line-ending characters. The solution might simply be more permissive comparison against the expected results.

**Comment by greg-1-anderson** [comment]
I tagged consolidation/output-formatters 3.1.13 with Symfony 4 support.

**Comment by greg-1-anderson** [comment]
I tagged consolidation/annotated-command 2.8.2 with Symfony 4 support.

**Comment by greg-1-anderson** [comment]
Now I have:
```
$ composer why symfony/console
codeception/base                    2.3.6       requires  symfony/console (>=2.7 <4.0)            
consolidation/annotated-command     2.8.2       requires  symfony/console (^2.8|^3|^4)            
consolidation/log                   1.0.5       requires  symfony/console (^2.8|^3|^4)            
consolidation/output-formatters     3.1.13      requires  symfony/console (^2.8|^3|^4)            
consolidation/robo                  dev-master  requires  symfony/console (^2.8|^3|^4)            
satooshi/php-coveralls              v1.0.2      requires  symfony/console (^2.1 || ^3.0 || ^4.0)  
stecman/symfony-console-completion  0.7.0       requires  symfony/console (~2.3 || ~3.0) 
```
I haven't made a PR for Robo with the composer.json changes yet, but I will shortly. Robo should be pretty much ready to go on Symfony 4, save for the fact that Codeception is pinning us to Symfony 3 due to its use of stecman/symfony-console-completion. If anyone wanted to try to get Symfony 4 support into stecman/symfony-console-completion, it would be appreciated.

**Comment by greg-1-anderson** [comment]
If you are using [Robo as a Framework](https://robo.li/framework), try requiring `"consolidation/robo": "dev-symfony-4"`. You should get Symfony 4 components, if there isn't anything else in your dependencies pinning you to Symfony 3.

Note that this is at the moment untested, as we are pinned to Symfony 3 by Codeception in our tests.

**Comment by Naktibalda** [comment]
Use 2.3 branch of Codeception for testing.

**Comment by greg-1-anderson** [comment]
@Naktibalda Same issue:
```
$ composer why symfony/console
codeception/base                    2.3.6       requires  symfony/console (>=2.7 <4.0)            
consolidation/annotated-command     2.8.2       requires  symfony/console (^2.8|^3|^4)            
consolidation/log                   1.0.5       requires  symfony/console (^2.8|^3|^4)            
consolidation/output-formatters     3.1.13      requires  symfony/console (^2.8|^3|^4)            
consolidation/robo                  dev-master  requires  symfony/console (^2.8|^3|^4)            
satooshi/php-coveralls              v1.0.2      requires  symfony/console (^2.1 || ^3.0 || ^4.0)  
stecman/symfony-console-completion  0.7.0       requires  symfony/console (~2.3 || ~3.0)          
$ composer why stecman/symfony-console-completion
codeception/base  2.3.6  requires  stecman/symfony-console-completion (^0.7.0)  
```

**Comment by Naktibalda** [comment]
Oh, you have a dependency on Codeception/base.
2.3 branch (not released yet) of Codeception/Codeception supports Symfony 4.

**Comment by greg-1-anderson** [comment]
I started using `"codeception/codeception": "2.3.x-dev"`, and I'm now making better progress:
```
$ composer why symfony/console
codeception/codeception          2.3.x-dev   requires  symfony/console (>=2.7 <5.0)            
consolidation/annotated-command  2.8.2       requires  symfony/console (^2.8|^3|^4)            
consolidation/log                1.0.5       requires  symfony/console (^2.8|^3|^4)            
consolidation/output-formatters  3.1.13      requires  symfony/console (^2.8|^3|^4)            
consolidation/robo               dev-master  requires  symfony/console (^2.8|^3|^4)            
satooshi/php-coveralls           v1.0.2      requires  symfony/console (^2.1 || ^3.0 || ^4.0)
```
However, all of the Symfony components are still 3.x.  Here's the next problem I found:
```
$ composer why symfony/event-dispatcher
codeception/codeception          2.3.x-dev   requires  symfony/event-dispatcher (>=2.7 <5.0)  
consolidation/annotated-command  2.8.2       requires  symfony/event-dispatcher (^2.5|^3|^4)  
consolidation/robo               dev-master  requires  symfony/event-dispatcher (^2.5|^3|^4)  
henrikbjorn/lurker               1.2.0       requires  symfony/event-dispatcher (^2.2|^3.0)
```
Maybe I can just remove `henrikbjorn/lurker` for testing.

**Comment by greg-1-anderson** [comment]
Moving along from there, I'm back to another Codeception component, this time `codeception/aspect-mock`:
```
$ composer why symfony/finder
codeception/aspect-mock          1.0.0       requires  symfony/finder (~2.4|~3.0)   
codeception/codeception          2.3.x-dev   requires  symfony/finder (>=2.7 <5.0)  
consolidation/annotated-command  2.8.2       requires  symfony/finder (^2.5|^3|^4)  
consolidation/output-formatters  3.1.13      requires  symfony/finder (^2.5|^3|^4)  
consolidation/robo               dev-master  requires  symfony/finder (^2.5|^3|^4)
```

**Comment by greg-1-anderson** [comment]
We require that directly. There's probably a dev component I can use.

**Comment by greg-1-anderson** [comment]
Better:
```
$ composer why symfony/finder
codeception/aspect-mock          dev-master  requires  symfony/finder (~2.4|~3.0|~4.0)  
codeception/codeception          2.3.x-dev   requires  symfony/finder (>=2.7 <5.0)      
consolidation/annotated-command  2.8.2       requires  symfony/finder (^2.5|^3|^4)      
consolidation/output-formatters  3.1.13      requires  symfony/finder (^2.5|^3|^4)      
consolidation/robo               dev-master  requires  symfony/finder (^2.5|^3|^4) 
```
Next up is grasmash/yaml-expander.

**Comment by greg-1-anderson** [comment]
@Naktibalda @DavertMik Robo is now ready for Symfony 4 components, pending updates to some of our dependencies. See https://github.com/consolidation/Robo/pull/651. Perhaps one of you could help out with the Codeception issues.
