### ISSUE TITLE
background(): Executes command in background mode (asynchronously)

### ISSUE THREAD

**Issue by jverdeyen** [consolidation/Robo#65]
Hi,

Is there a way to run a command in the background but wait for it to "start up".
I'm starting a php internal webserver and phantomjs driver, but behat testing fails in the first 5-10 cases because both server and phantomjs aren't started yet.

Or should this be a process in the background?

Thx!

**Comment by greg-1-anderson** [comment]
Closed due to lack of activity. Re-open as needed.
