### ISSUE TITLE
"The provided cwd does not exist" Exception thrown after update to Symfony 3.4

### ISSUE THREAD

**Issue by mcera** [consolidation/Robo#652]
### Steps to reproduce
ComposerInstall Task has been executed as part of the build process in the following way: 

chdir(self::WORKING_DIR);
$this->taskComposerInstall()->optimizeAutoloader()->noDev()->noInteraction()->run();

composer.json and .lock are already copied into the WORKING_DIR
### Expected behavior
Composer should create the vendor directory and dependencies into the WORKING_DIR

### Actual behavior
Exception is thrown with a message "The provided cwd does not exist." and call stack:

#0 C:\Apache24\htdocs\DSCA-Diagnosia\vendor\symfony\symfony\src\Symfony\Component\Process\Process.php(210): Symfony\Component\Process\Process->start(Object(Closure), NULL)
#1 C:\Apache24\htdocs\DSCA-Diagnosia\vendor\consolidation\robo\src\Common\ExecTrait.php(330): Symfony\Component\Process\Process->run(Object(Closure))
#2 C:\Apache24\htdocs\DSCA-Diagnosia\vendor\consolidation\robo\src\Common\ExecCommand.php(139): Robo\Task\Composer\Base->execute(Object(Symfony\Component\Process\Process))
#3 C:\Apache24\htdocs\DSCA-Diagnosia\vendor\consolidation\robo\src\Task\Composer\Install.php(38): Robo\Task\Composer\Base->executeCommand('call C:\\Program...')
#4 C:\Apache24\htdocs\DSCA-Diagnosia\vendor\consolidation\robo\src\Collection\CollectionBuilder.php(522): Robo\Task\Composer\Install->run()
#5 C:\Apache24\htdocs\DSCA-Diagnosia\vendor\consolidation\robo\src\Collection\CollectionBuilder.php(506): Robo\Collection\CollectionBuilder->runTasks()
#6 C:\Apache24\htdocs\DSCA-Diagnosia\RoboFile.php(91): Robo\Collection\CollectionBuilder->run()
#7 C:\Apache24\htdocs\DSCA-Diagnosia\RoboFile.php(39): RoboFile->composerInstall()
#8 [internal function]: RoboFile->build(Array)

### System Configuration
Windows 7, PHP 7.1, Symfony 3.4, Robo 1.1.5

RuntimeException occurs only with Symfony 3.4.* and in a previous version (3.3.14) everything worked well.

**Comment by greg-1-anderson** [comment]
Instead of using `cwd`, try `$this->workingDir(self::WORKING_DIR)` instead and see if that works better.

**Comment by mcera** [comment]
Adding --working-dir didn't help. I think error occurs prior to the command execution.
That is the purpose why I have tried to change working directory of command $this->taskComposerInstall()->**dir**(self::WORKING_DIR)->... and this task now executes successfully.

Also two other tasks needed dir() method to work: taskSvnStack,  taskExec. 

Is it possible in Robo to define working directory globally?

This changes in Symfony are to blame:
https://github.com/symfony/process/commit/e146aa7652904b7ccf061f24776012fca1ea1ba7#diff-9a01fc0e340da4c3f1e4a16029a63977

**Comment by JKingweb** [comment]
I'm similarly unable to use taskServer even after invoking its `dir()` method. Running PHP 7.0 on Windows 10, with Robo 1.1.5 and (it appears) Symfony 3.4.1.

I don't get a call stack, but maybe I need to toggle a debug option to get that? This is my input and output:

```php
class RoboFile extends \Robo\Tasks
{
    public function test(array $args) {
        $testPath = __DIR__.\DIRECTORY_SEPARATOR."tests".\DIRECTORY_SEPARATOR;
        // start the built-in PHP server
        $this->taskServer(8000)->host("localhost")->dir($testPath."docroot")->arg($testPath."server.php")->run();
    }
}
```

```
>vendor\bin\robo test
 [Development\PhpServer] Running php -S localhost:8000 -t path\to\files "path\to\router.php"
 [error]  The provided cwd does not exist.
```

This is my very first experience with Robo, so I guess I picked the wrong week to try it out...

**Comment by greg-1-anderson** [comment]
@JKingweb Did you install Robo from source? The 1.1.5 robo.phar should still contain Symfony 3.3.

I'd also expect that you'd get Symfony 3.3 if you pulled Robo sources via git and then ran `composer install` to install from the lock file. If not, you could try pinning the Symfony process version via `composer require symfony/process:^3.3.0`.

I haven't had a chance to try to reproduce or fix this yet.

**Comment by JKingweb** [comment]
Thanks for the suggestions. I did manually require symfony/process 3.3.* after posting here and pondering the matter a bit, and that works just fine in the interim. 

I really like Robo. It's exactly what I was looking for.

**Comment by greg-1-anderson** [comment]
The Symfony/Process 3.4.x failure identified here appears to be limited to the Windows platform.

I made an issue to track this (https://github.com/symfony/symfony/issues/25446, cross-linked above).

**Comment by greg-1-anderson** [comment]
Looks like the problem with Symfony/Process 3.4.x will clear itself up in the next tagged release.

Robo will need to adjust for Symfony 4.x -- or perhaps we will just ensure that Symfony 3.x is in our lock file, and require that any apps that use Robo as a framework must conform to Symfony 4 conventions (and provide a working directory any place that Symfony/Process is required).
