### ISSUE TITLE
[feature] Task for envsubst

### ISSUE THREAD

**Issue by kmajzlik** [consolidation/Robo#657]
### Expected behavior
I would like to easily use `envsubst` command.

Typical usecase: create local.yml from example.yml (in Dockerized environment).

**Comment by verbruggenalex** [comment]
This possibly provides a solution: https://github.com/nordcode/robo-parameters

**Comment by greg-1-anderson** [comment]
Thanks, @verbruggenalex. It is better to provide features such as this in external libraries such as the one suggested above.
