### ISSUE TITLE
Renamed to robo won't run

### ISSUE THREAD

**Issue by szepeviktor** [consolidation/Robo#661]
as robo.phar it runs OK but when moved to ~/bin/robo:

```
PHP Fatal error:  Uncaught Error: Class 'Robo\Runner' not found in /home/viktor/bin/robo:21
Stack trace:
#0 {main}
  thrown in /home/viktor/bin/robo on line 21
```

PHP 7.0.26

**Comment by szepeviktor** [comment]
Cause: https://github.com/consolidation/Robo/blob/master/robo#L9

**Comment by szepeviktor** [comment]
Please see https://github.com/wp-cli/wp-cli/blob/master/php/boot-phar.php

**Comment by theofidry** [comment]
Heads up: [Humbug Box](https://github.com/humbug/box) has been released and I believe is way easier to use to build PHARs: it requires little config and takes care of a lot of annoying things for you (e.g. excluding tests files, setting phar.readonly=0, bumping the memory or number of opened files limit if necessary). If interested feel free to ping me

**Comment by greg-1-anderson** [comment]
I tested with `\Phar::running()`, and it worked, so I committed the change.

@theofidry: I converted [g1a/starter](https://github.com/g1a/starter), the recommended way for folks to start a new Robo-as-a-framework project, to use humbug/box.

**Comment by szepeviktor** [comment]
Thank you.
