### ISSUE TITLE
Additional global options

### ISSUE THREAD

**Issue by daaru00** [consolidation/Robo#678]
Hi,

it is possible to declare additional global options like `robo --rootPath=/other/path <command> <args>`?

I tried to manipulate the application input definitions:
```php
        // Add options
        Robo::application()->getDefinition()->addOption(new InputOption('--rootPath', '-p', InputOption::VALUE_OPTIONAL, 'Root path'));

        // Rebind definitions
        Robo::input()->bind(Robo::application()->getDefinition());

        // Check config option
        $rootPath = Robo::input()->getOption('rootPath');
```
but I breaked the command definition, it seems now it expect:
`robo <command> <command> <args>`

What's the cleanest way to do this? It is possibile maybe using directly `Symfony\Component\Console\Input\ArgvInput`?

Thanks!

**Comment by greg-1-anderson** [comment]
The doubling up of `<command>` is caused by calling `$input->bind()` directly. Avoid doing that, and you should be fine.

Drush add global options like so: https://github.com/drush-ops/drush/blob/a7814d2afcf13236455f509679c74f77fc933700/src/Application.php#L50:L104

**Comment by daaru00** [comment]
Hi,
>The doubling up of <command> is caused by calling $input->bind() directly. Avoid doing that, and you should be fine.

I try, but if I don't call the bind operation no options is defined
```php
        // Add options
        Robo::application()->getDefinition()->addOption(new InputOption('--rootPath', '-p', InputOption::VALUE_OPTIONAL, 'Root path'));
        
        print_r(Robo::input()->getOptions());

        // Check config option
        $rootPath = Robo::input()->getOption('rootPath');
```
The `getOptions` method return an empty array
```
Array
(
)
```
and then it raise an `Symfony\Component\Console\Exception\InvalidArgumentException` : The "rootPath" option does not exist.

> Drush add global options like so: https://github.com/drush-ops/drush/blob/a7814d2afcf13236455f509679c74f77fc933700/src/Application.php#L50:L104

Thanks for the great use case example, personally I'm trying to extend the Robo application without rewriting the whole application following ["Robo as a Framework" guide](https://robo.li/framework/#using-your-own-dependency-injection-container-with-robo-advanced)

**Comment by daaru00** [comment]
Maybe I found the problem, I tryng to do this in the command constructor (type of Robo\Tasks) and I noticed that the input bind definition is not done before the run.
The problem is time and not the code :)

So, I discover that maybe even Robo has the same problem, it use a custom argument parser:
https://github.com/consolidation/Robo/blob/master/src/Runner.php#L401

If I want to do some preflight operation I need to parse the arguments by myself (following the Robo's raws posted before).

**Comment by greg-1-anderson** [comment]
It wasn't clear to me that you were trying to do this in a RoboFile. All of the command hooks that are available are called after `$application->run()`, which is too late to define more options. You could try `@hook option *` and see if that works for you. Maybe the RoboFile constructor might work.

**Comment by daaru00** [comment]
I'm sorry, I can't find the hook's documentation. 
It would be very convenient for me to have a command initiation hook :+1:

**Comment by greg-1-anderson** [comment]
See https://github.com/consolidation/annotated-command#hooks. There is a `@hook init`
