### ISSUE TITLE
Add the ability to have commands that are just wrappers for other commands

### ISSUE THREAD

**Issue by rodrigoaguilera** [consolidation/Robo#706]
### System Configuration
Debian testing with php 7.2 and robo 1.2.2

### Steps to reproduce
I am trying to write a tool to facilitate development with docker using robo as a framework.

The final goal is that we can write "`mytool drush cr --help`" for example. instead of "`docker-compose exec --user=www-data web drush cr --help`"

I have a task like this.
```php
  /**
   * Wrapper around drush
   */
  public function drush (array $args)
  {
    return $this->taskExec('docker-compose')
      ->arg('exec')
      ->arg('--user=www-data')
      ->arg('web')
      // Without the sh wrapping the exit code is non-zero.
      ->arg('sh')
      ->arg('-c')
      ->arg('/var/www/vendor/bin/drush ' . implode(' ', $args))
      ->run();
  }
```
In this case the --help flag is picked up by robo and it doesn't run the command at all.

### Expected behavior
Have the possibility to have some command that receive all the arguments and options as pass-through just if you called `robo command -- moreargs`. 

### Actual behavior
I need to run "`mytool drush -- cr --help`" to be able to run the drush command properly.

Maybe I am missing something to achieve this. An idea can be to have some annotation for commands that need this and change the logic where the options and arguments are parsed so for this commands it would be as if "--" was passed after the command name.

Does it makes sense?

**Comment by greg-1-anderson** [comment]
Robo does support `--`, which causes everything on the commandline that appears after it to be interpreted as an argument instead of a flag. However, its use is not optional; you would have to convert your example to:
```
mytool drush -- cr --help
```

**Comment by rodrigoaguilera** [comment]
Thank you for your attention.

Since I am using robo as a framework my idea right now is to modify the argv array before calling robo to add "--" as a third element for a set of configured commands before calling robo.

I tried `@hook init drush` annotation but the parsing of options is already done so its too late.

Any ideas so I can avoid writing "--" for commands that I just want to pass all arguments and flags to another command like in the example?

I am also willing to dive into the code but want to know first if what I want to achieve falls into the scope of robo.

**Comment by greg-1-anderson** [comment]
I tend to think that your use case does not fit well with Robo. If you have flags for your application, then how would you differentiate them from the flags for Drush?  If you do not have any flags, and you only have one command (exec the first argument), then perhaps you do not need any of the features of Robo as a Framework, and you'd be better off with your own runner.

Note that you could still use Robo tasks in your application, even if you did not use the Robo runner, as long as you initialize the DI container before running any tasks.

**Comment by greg-1-anderson** [comment]
FYIO, Robo does something similar to what you are trying to do here: https://github.com/consolidation/Robo/blob/master/src/Runner.php#L401

It would be possible for you to do something similar before you called the Robo runner if you really needed / wanted to use that for some reason.

**Comment by rodrigoaguilera** [comment]
Thank you so much for the assistance. Robo is an awesome tool
I think I will handle the "passthrough" commands with a bit of logic before calling the robo runner

**Comment by greg-1-anderson** [comment]
Yeah, if you just want to make some simple wrapper commands that pass through to existing / other commandline tools (some of which may be written with Robo), you might consider [Ahoy-cli](https://github.com/ahoy-cli/ahoy)
