### ISSUE TITLE
Use any psr/container?

### ISSUE THREAD

**Issue by shadowhand** [consolidation/Robo#733]
I haven't dug deep enough into Robo internals to figure out why Robo forces usage of `league/container` instead of allowing for any `psr/container` to be used, while still defaulting to `league/container` if none is provided.

Are there plans to adopt a more neutral container implementation? I'd really like to have my Robo tasks using our existing container so that I can access application internals when necessary.

**Comment by greg-1-anderson** [comment]
Robo makes use of the inflection feature of `league/container`, which is not part of the `psr/container` standard.

Note that `league/container` supports [delegate containers](http://container.thephpleague.com/2.x/delegates/); you could install your existing container as a delegate of the Robo league/container. If you do this, then your tasks will have access to any object available in either container.
