### ISSUE TITLE
How to find RoboFile.php with global binary symlink

### ISSUE THREAD

**Issue by dragoonis** [consolidation/Robo#749]
As per the project docs, you can symlink `robo` to `project/vendor/bin/robo`.

However when I type `robo` it doesn't know where to find my RoboFile, and so I just get the generic robo output, and none of my project's tasks are shown.

project name is `dcop`
I only see my tasks when I do:

```
cd customername-dcop/dcop_toolkit
dcop
```

This isn't good DX as i want the developers to be able to run `dcop` command wherever they are on their terminal.

**Comment by DavertMik** [comment]
You can specify exact path to RoboFile with:

```
robo --load-from path/to/RoboFile.php
```

**Comment by dragoonis** [comment]
@DavertMik 

I'm currently doing this:
```
  sudo ln -sf "${PROJECT}/dcop_toolkit/vendor/bin/robo" /usr/local/bin/dcop
  sudo chown $UID /usr/local/bin/dcop
```

I don't think it's possible to have --load-from into here, is it?

What alternative options are there, so when `dcop` is typed then it does:
```
${PROJECT}/dcop_toolkit/vendor/bin/robo --load-from ${PROJECT}/dcop_toolkit/RoboFile.php
```

**Comment by greg-1-anderson** [comment]
It should also be looking for RoboFile.php in the cwd. Is this not working?

As for your other question, instead of using a symlink, you could use a Bash alias:
```
alias dcop="${PROJECT}/dcop_toolkit/vendor/bin/robo --load-from ${PROJECT}/dcop_toolkit/RoboFile.php"
```
That evaluated ${PROJECT} at the time the alias is defined. I'd have to experiment to see if it worked right to evaluate it later (e.g. by using single quotes). If that doesn't work, then you could use a bash function instead of an alias.

**Comment by dragoonis** [comment]
I tried with an alias initially.

I've tried this:
```
  alias dcop="${PROJECT}/dcop_toolkit/vendor/bin/robo --load-from=${ROBOFILE_PATH}"
  . ~/.bash_profile
```

I get the error:
`./setup.sh: line 13: dcop: command not found`

If we can find out why the setup.sh can't resolve `dcop` then i'll be very happy!

**Comment by greg-1-anderson** [comment]
As long as you define dcop before you run setup.sh it should be fine. Type `alias dcop` to see its current definition.

Also, note that you use `"` in one of your examples above, and `"` in the other. The behavior of the alias changes based on which quote you use.

**Comment by dragoonis** [comment]
@greg-1-anderson 
turns out bash doesn't support aliases by default (as it's non-interactive) and you need to do a `shopt` thing .. I didn't get it working in the end.

I cheated a bit and inside the bash script just use `DCOP_COMMAND` done this in the end:

```
DCOP_COMMAND="${PROJECT}/dcop_toolkit/vendor/bin/robo --load-from=${ROBOFILE_PATH}"

function setup_dcop_project() {
  ${DCOP_COMMAND} env_setup
}


function install_frontend() {
  ${DCOP_COMMAND} composer
  ${DCOP_COMMAND} frontend_node_setup
  ${DCOP_COMMAND} frontend_node_gen
}

function setup_dcop_command() {
    if [[ "$SHELL" == *"zsh"* ]]; then
    echo "alias dcop='${PROJECT}/dcop_toolkit/vendor/bin/robo --load-from=${ROBOFILE_PATH}'" >> ~/.zshrc
  else
    echo "alias dcop='${PROJECT}/dcop_toolkit/vendor/bin/robo --load-from=${ROBOFILE_PATH}'" >> ~/.bash_profile
  fi
}

setup_dcop_project

**Comment by dragoonis** [comment]
Issue resolved.

**Comment by greg-1-anderson** [comment]
Glad you found a solution. You should be able to replace `${DCOP_COMMAND}` with `robo` if you defined `function robo() {` instead of the string-alias-thing you're using, but that's clearly optional.
