### ISSUE TITLE
Issues with env() in Exec

### ISSUE THREAD

**Issue by q0rban** [consolidation/Robo#768]
### Steps to reproduce
1. Create a task that executes the `env` command. Note the environment variables.
2. To this task, add a call to `->env('FOO', 'BAR')`. Note that many of the above environment variables are missing.
3. Add an additional call to `->env('BAR', 'BAZ')`. Note that `FOO=BAR` is now missing from the environment variables.

### Expected behavior
1. Using `->env()` should inherit existing environment variables. (This will be default behavior in Symfony 4)
2. Calling `->env()` more than once should not remove previously set environment variables.

### Actual behavior
1. Many of the existing environment variables are removed, including on some environments things like `PATH` which can break the execution of certain scripts. (For example, a script that calls `#!/usr/bin/env php` might fail if PATH is missing with `php not found`)
2. Previously set environment variables in a Robo task are wiped out.

### System Configuration
MacOS, PHP 7.2

**Comment by greg-1-anderson** [comment]
A PR for this would be welcome.
