### ISSUE TITLE
g1a/composer-test-scenarios should be a dev dependency

### ISSUE THREAD

**Issue by mglaman** [consolidation/Robo#782]
### Steps to reproduce
Add Robo as a dependency to my project.

### Expected behavior
Have only required dependencies

### Actual behavior
g1a/composer-test-scenarios is a non-dev dependency, however it looks to be a dev one.

**Comment by greg-1-anderson** [comment]
Yes, it should, but there's a bug. I worked around the bug by moving the component to `require`. It won't be there forever; I'll move it back once I fix the bug in g1a/composer-test-scenarios.

**Comment by mglaman** [comment]
Cool! Thanks. Just doing an audit of our `--no-dev` install :)

**Comment by greg-1-anderson** [comment]
Here's the commit reference: 1ef19cef32d05146507554f1c9fe3cf90ca44684

Once I have time, I'll make composer-test-scenarios a Composer plugin, and it will then work correctly (do nothing) in `--no-dev`

**Comment by greg-1-anderson** [comment]
Fixed in #803.

**Comment by greg-1-anderson** [comment]
Released Robo 1.3.2 with composer-test-scenarios back in the `require-dev` section.
