### ISSUE TITLE
Robo does not find Codeception

### ISSUE THREAD

**Issue by pkollitsch** [consolidation/Robo#786]
### Steps to reproduce
- Install codeception via composer locally
- Install robo via composer locally
- both are found in in `./bin/` because of composer.json config `"bin-dir": "bin",`
- added sample function `do` to run codeception test (`$this->taskCodecept()->suite('unit')->run();`)
- `./bin/codecept run unit` runs unit tests that are configured

### Expected behavior
running `./bin/robo do` should run codeception

### Actual behavior
An error comes up that codecept can't be found:

```
[error]    in task Robo\Task\Testing\Codecept 
Neither composer nor phar installation of Codeception found.
```

### System Configuration
- ubuntu 18.04
- php 7.2.10

**Comment by greg-1-anderson** [comment]
Robo has its own searchpath rules for running binaries, and it seems it does not respect the `bin-dir` settings. Possible solutions would include enhancing Robo's bin dir locating code, or use `composer exec` to run tools (conditionally)?   PRs welcome.

Workaround: Don't relocate the bin dir, or drop a symlink from `vendor/bin` to the bin dir.

**Comment by pkollitsch** [comment]
Thank you. The symlink works fine.
