### ISSUE TITLE
Question: How to fail a robo call 

### ISSUE THREAD

**Issue by pkollitsch** [consolidation/Robo#790]
### Steps to reproduce
I am sure this is just a question and not a bug. I have the following function in my RoboFile (abbreviated, there are more execs in the stack):

```    
public function qualitycontrol()
    {
        $this->taskExecStack()
             ->stopOnFail()
             ->exec(
                 'phpcpd --progress app/api5/Boka10 --min-lines=2 --min-tokens=30'
             )
             ->run();
        $this->phpstan(7);
    }
```
### Expected behaviour
I would expect the call to `robo qualitycontrol` to fail completely if phpcpd returns a fail code. 

### Actual behaviour
phpcpd (taskExecStack) returns a fail code and stops executing following stack items and then `$this->phpstan(7)` is run.

- Robo 1.3.1
- PHP 7.2.10
- Ubuntu 18.10 (yep, I did that ;)

**Comment by greg-1-anderson** [comment]
The best way to handle this is to use a task collection. If any task fails, then the other tasks in the collection are not executed. Return the result of the collection as the function result of your command.

See the [examples](https://github.com/consolidation/Robo/blob/1.3.1/examples/src/Robo/Plugin/Commands/ExampleCommands.php#L354).
