### ISSUE TITLE
Better link to Symfony Console Styles

### ISSUE THREAD

**Issue by davidsneighbour** [consolidation/Robo#819]
### Steps to reproduce
Trying to find info about available `$this->io()->`-methods. Going to the [Getting Started documentation page](https://robo.li/getting-started/), [scroll to section "IO"](https://robo.li/getting-started/#io), clicking the link to Symfony Console Styles in the following paragraph:

This allows Robo scripts to follow the [Symfony Console Style Guide](http://symfony.com/blog/new-in-symfony-2-8-console-style-guide) if desired.

### Expected behaviour
We end up on a page detailing documentation of the available method

### Actual behaviour
We end up on a blog post with a screenshot of methods, but no documentation

### System Configuration
Generic

### Note

A better link instead of the one above would be the following:

https://symfony.com/doc/current/console/style.html

**Comment by greg-1-anderson** [comment]
Thanks for the suggestion
