### ISSUE TITLE
 Class Robo\Tasks contains 2 abstract methods and must therefore be declared abstract

### ISSUE THREAD

**Issue by borgogelli** [consolidation/robo#824]
+ php -v
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
+ robo -V
Robo 1.4.0
+ robo test
PHP Fatal error:  Class Robo\Tasks contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Robo\Contract\IOAwareInterface::setIOStorage, Robo\Contract\IOAwareInterface::resetIO) in /home/jenkins/workspace/iubar-paghe-test/php-iubar-builder/vendor/consolidation/robo/src/Tasks.php on line 10

**Comment by greg-1-anderson** [comment]
I can't reproduce this with HEAD of the 1.x branch or via `checkout 1.4.0`. I'm using php 7.3, but that shouldn't produce different results than 7.2 here.

`IOAwareInterface::setIOStorage` was part of the Robo 1.3.5 release where I was trying to make changes on the 1.x branch to prepare for Robo 2.x. I was trying to keep 1.3.5 compatible vis-a-vis the public APIs, but several clients were directly using protected fields, so I backed out 1.3.5 and tagged 1.4.0. `setIOStorage` and friends moved to the master branch for Robo 2.x.

When I run `robo --version` on the 1.4.0 tag, I get `1.3.6-dev` (a mistake). What commit are you on to get version 1.4.0? Once we can figure out what is going on here, I'll tag 1.4.1 to fix the problem.

**Comment by borgogelli** [comment]
The problem arised with the 1.3.0 version after some system upgrade, probably of php or one of its dependencies. (I have the bad habit to launch 'apt-get update && apt-get upgrade' ). So today, I have tried to download the latest phar from http://robo.li/robo.phar and the problem persists.
As soon as will be a new release I will try it. Thank you Greg.

**Comment by borgogelli** [comment]
Now  (02/01/2019, 20:49 GMT+2)
+ wget http://robo.li/robo.phar 
+ robo -V
Robo 1.3.0
Is it right ?

**Comment by greg-1-anderson** [comment]
When I download the Robo phar, I get 1.4.0, which also isn't right. It looks like the 1.4.1 release is broken; something I didn't think I changed is not working. Will look into that.

Another interesting problem is that `robo self:update` now goes to Robo 2.0.0-alpha1, which probably isn't what most people are going to want.  To avoid that problem, I deleted that release, but in the long term I'll need to figure out how to do future releases without messing up most of the users who will still be on the stable branch. A modification to the self:update command is probably in order.

**Comment by greg-1-anderson** [comment]
OK, the 1.4.3 release seems to finally have resolved these issues. If you re-download https://robo.li/robo.phar, you should find that it reports version 1.4.3 and works correctly.

**Comment by greg-1-anderson** [comment]
There was a bug where Robo would load the autoloader from any robo.phar in the current working directory. That was also interfering with the 'release' script. I fixed that in 1.4.3.

**Comment by borgogelli** [comment]
Great. Thank you Greg.

**Comment by borgogelli** [comment]
Robo is a great tool and could be used in a CI pipeline too, as we usually do every days. I'm sure Robo wil grow in popularity as CI tool, but it's important that its releases are stable and support is fast when there is some evident bug. And your support has been always great. Thank you again. Bye.

**Comment by greg-1-anderson** [comment]
I'm working on some improvements for Robo 2.x that should improve maintainability and stability.

For a highly customized Robo experience, you can make a custom application that uses Robo as a framework. See [g1a/starter](https://www.github.com/g1a/starter) for a fast way to start up a new tool or php library.
