### ISSUE TITLE
Allow custom behaviour

### ISSUE THREAD

**Issue by ScreamingDev** [consolidation/Robo#829]
### Steps to reproduce

```
robo db:reset
```

### Expected behavior

Robo shall fail:

> This is the production-site dumbo!

### Actual behavior

Live site goes down. All data since last backup lost.

### Details

There are a few things that can solve this:

* Use classic OOP and override the method that wraps the actual call (not possible as the CommandProcessor is not in our hands).
* Have a pre and post Method that Robo looks up and executes before/after each command (this is simple and would add huge flexibility).

But in the end (and not only for this scenario) Robo should allow more custom things.

**Comment by greg-1-anderson** [comment]
@ScreamingDev This is already supported.

- Classic OOP:
```
$commandProcessor = \Robo\Robo::service('commandProcessor');
$commandProcessor->hookManager()->addValidator(new MyValidator );
```
Hm, this does not appear to be documented. However, if you use [robo as a framework](https://robo.li/framework) to build your own phar, then you can inject the command processor into any object that needs it (or just set up your validator as shown above when setting up your own DI container). See https://github.com/g1a/starter.

- Pre and Post methods using annotations:
```
/**
 * @hook validate db:reset
 */
public function validatePassword(CommandData $commandData)
{
    if ($this->myLiveCheck()) {
        throw new \Exception("Not on the live server you don't!");
    }
}
```

See the [validate hook documentation](https://github.com/consolidation/annotated-command#validate-hook).

**Comment by ScreamingDev** [comment]
Hm. I must have been blind while reading https://robo.li . Thanks for the hint, works like a charm!
