### ISSUE TITLE
Using Local Trait with Global Robo

### ISSUE THREAD

**Issue by albertski** [consolidation/Robo#835]
I have a global library that extends Robo which allows me to add command globally.

    <?php
    namespace MyGlobalRobo\MyGlobalRobo;
    use Robo\Tasks as Tasks;
    /**
     * Base class for Xeno robo commands.
     */
    class BaseDrupalD8 extends Tasks {

      // A lot of custom commands.
    }

It works perfectly but the problem I am running into is that I need to include a Trait that is local in my project. This is how my RoboFile.php looks like:

    <?php

    use MyGlobalRobo\MyGlobalRobo\BaseDrupalD8;

    /**
     * This is project's console commands configuration for Robo task runner.
     *
     * @see http://robo.li/
     */
    class RoboFile extends BaseDrupalD8 {

      use \MyLocal\Robo\ConfigHelperTrait;
      use \MyLocal\Robo\Task\loadTasks;
      use \MyLocal\Robo\TokenReplaceTrait;

      /**
       * Build the website
       */
      public function build() {
        $this->buildBootstrap();
        $this->buildSass();
      }

    }

If I try to run the build command I get the following error:

    Fatal error: Trait 'MyLocal\Robo\ConfigHelperTrait' not found in /Users/myuser/Sites/mysite/RoboFile.php on line 12

composer.json autoload is set:

```
autoload": {
  "psr-4": {
    "MyLocal\\": "src/",
  }
},
```

Could it be that I can't add local files since I am doing it globally?

**Comment by greg-1-anderson** [comment]
Where is your composer.json file? The composer.json file that you must modify is the one that is in your global Robo. It is impossible to do this if you are using the Robo phar. Install Robo with composer, and then add your global library to your global Robo via `composer require`.

Your other option is to build your own phar. See [g1a/starter](https://github.com/g1a/starter)

**Comment by albertski** [comment]
Thanks @greg-1-anderson.  I actually have the autoload additions to composer.json in my local composer file.  I agree with you that it is not possible but just wanted to double check.
