### ISSUE TITLE
Codeception binary not found in PHAR

### ISSUE THREAD

**Issue by davidsneighbour** [consolidation/Robo#836]
### Steps to reproduce
I create a PHAR file based on the documentation at https://robo.li/framework/

### Expected behavior
Running a codeception task should find the codeception binaries in ./vendor/bin/ inside of the PHAR
```
        $this->taskCodecept()
             ->suite('unit')
             ->run();
```
### Actual behavior
Codeception can't be found:
```
 [error]    in task Robo\Task\Testing\Codecept 
  Neither composer nor phar installation of Codeception found. 
```

### System Configuration
Ubuntu 18.10 and PHP 7.2.10

**Comment by greg-1-anderson** [comment]
Hm, I am not sure this is (or should be) supported. @DavertMik , what do you think?

**Comment by davidsneighbour** [comment]
No need then [year end cleanup :)]
