### ISSUE TITLE
Feature: Add changed file as callback parameter in Base/Watch task

### ISSUE THREAD

**Issue by davidsneighbour** [consolidation/Robo#845]
Currently, the Base/Watch task allows no parameters for the `$callable` method that is called when a file in a watched directory changes. It would be nice to have the file(s) that were changed added as a parameter so that selective action can be taken. 

Example: I am watching a directory with many classes in subfolders for changes and run a static checker like Psalm over it when files change. Due to the number of files, it takes a long time. Better will be if the analyzer runs only over the changed file. 

I understand that Lurker is used for the monitor, but I don't see (or understand the library well enough to see) any way to return a file or array of changed files. It might not be possible with Lurker? Is there any knowledge as to how performance is influenced if I would traverse through my files and add a monitor() for every single file?

**Comment by greg-1-anderson** [comment]
I'm not very familiar with Lurker either. Adding a lot of monitors sounds like a bad solution. I'd be open to using a different library for watch if Lurker does not have the capabilities to provide this feature.

**Comment by davidsneighbour** [comment]
It appears this feature _is already_ available via Lurker:

```
$this
    ->taskWatch()
    ->monitor(
        static::$rootdir . '/src/Boka10/',
        function ($event) {
            $resource = $event->getResource();
            $this->qiPhpstan((string)$resource);
        },
        FilesystemEvent::ALL
    )
    ->run();
```

The parameter $event will receive an object that contains the way the type of file change (modify, add, delete) and more info and [seems to be a standard Symfony file resource object](https://api.symfony.com/3.1/Symfony/Component/Config/Resource/FileResource.html) (I never used Symfony before). 

Running `$event->getResource()` results in an object:

```
class Lurker\Resource\FileResource#1141 (1) {
  private $resource =>
  string(56) "/***/src/Boka10/Object13.php"
}
```

So with a little bit of typecasting, I can receive the changed files and work on just them in the response.

The above might be a nice addition to the documentation. I just need to find out what the proper way of casting a private property to string is. The `(string)` part in my example feels hacky.

Another investigation needs to go into what happens when multiple files are changing. Does it return one object with multiple file resources or multiple objects with one resource each. The latter probably will block each other in runs further down the line.

For now, the hacky way in the first snippet speeds my watch task up good enough.

**Comment by amitaibu** [comment]
In my case, where I try to monitor a directory, I see that the `$event` we are getting is actually of type `Symfony\Component\EventDispatcher\Event`

```php
    $this->taskWatch()
      ->monitor(
        '.',
        function(Event $event) {
          $resource = $event->getResource();
          $this->say((string) $resource);
        },
        FilesystemEvent::ALL
      )->run();
```

Checked it also on a single file, and I still get it as Event. @davidsneighbour Can you please confirm that (if so, I'll create a PR to type hint the argument, and change the link to the docs)

**Comment by davidsneighbour** [comment]
The EventDispatcher class does not have `->getResource()`. I am sure that the EventDispatcher is involved, but `$event` (I named it so because I came over it while diving deep on the changed file issue) is a file resource object. It states so if I var_dump $event inside of the function.

**Comment by amitaibu** [comment]
> The EventDispatcher class does not have ->getResource()

You are right. I wonder how my above code worked then, with the type hinting - I'll have to dig a bit

**Comment by davidsneighbour** [comment]
It's most probably this one: https://github.com/symfony/symfony/blob/3.1/src/Symfony/Component/Config/Resource/FileResource.php

All the methods in there worked when I spent a weekend a while ago ;) have fun digging.
