### ISSUE TITLE
PhpDoc: return interface vs. class

### ISSUE THREAD

**Issue by davidsneighbour** [consolidation/Robo#848]
This is a weird situation and I am not sure if Robo is the one to blame, but let's start it here, I have the feeling it's a PhpDoc issue ;)

I am using the latest release version of Robo with PHP7.2 and [phpstan](https://github.com/phpstan/phpstan) (for code analysis) in it's latest version. 

In one of my classes I have the following code:

```
    /**
     * Create a connection object and return it.
     *
     * @param mixed[] $setup
     * @return \Robo\Collection\CollectionBuilder
     */
    private function getRsynchObject(array $setup): \Robo\Collection\CollectionBuilder
    {
        $synch = $this->taskRsync();
        $synch->recursive()
            ->excludeVcs()
            ->progress()
            ->stats()
            ->delete()
            ->exclude($this->excludePattern)
            ->checksum()
            ->rawArg('-l')
            ->wholeFile()
            ->compress()
            ->verbose();

        // remote system has a special port for ssh connections
        if (isset($setup['sshport'])) {
            $synch->rawArg("-e 'ssh -p " . $setup['sshport'] . "'");
        }

        return $synch;
    }
```

This code works as expected. It's supposed to setup a rsync task that I reuse on several places. The issue arises with the return typehint. This code above works. Using `phpstan` raises errors as follows:

```
Method Booka\Tasks\Staging::getRsynchObject() should return Robo\Collection\CollectionBuilder but  
         returns Robo\Task\Remote\Rsync.   
```

Now, if I change the typehints from `\Robo\Collection\CollectionBuilder` to `Robo\Task\Remote\Rsync` phpstan is happy, but PHP is not:

```
ERROR: Uncaught TypeError: Return value of Booka\Tasks\Staging::getRsynchObject() must be an instance of Robo\Task\Remote\Rsync, instance of Robo\Collection\CollectionBuilder returned in phar:///home/patrick/Projects/BooKa/app/booka/src/Tasks/Staging.php:301
Stack trace:
#0 phar:///home/patrick/Projects/BooKa/app/booka/src/Tasks/Staging.php(256): Booka\Tasks\Staging->getRsynchObject(Array)
#1 phar:///home/patrick/Projects/BooKa/app/booka/src/Tasks/Staging.php(100): Booka\Tasks\Staging->synch(Array)
#2 [internal function]: Booka\Tasks\Staging->synchUp(Array)
#3 phar:///home/patrick/Projects/BooKa/app/booka/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#4 phar:///home/patrick/Projects/BooKa/app/booka/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 phar:///home/patrick/Projects/BooKa/app/booka/vendor/consolidati 
in phar:///home/patrick/Projects/BooKa/app/booka/src/Tasks/Staging.php:301
```

Meaning, that the first version of typehint was right. As far as I understand Robo's code `CollectionBuilder` is an interface and `Rsync` is a class. I am aware of people telling us to use interfaces as return types as "good coding style" but... hmm...

Would you categorise this as documentation issue in Robo or a bug in PhpStan? I would open an issue with same content in PhpStan, but for now don't want to spam issues all over the place ;)

**Comment by davidsneighbour** [comment]
sidenote 1: the SSH task has a similar issue.
sidenote 2: I am aware that I can suppress these errors, but trying to get to the bottom of this "issue" to understand it for later work. don't treat this as urgent issue.

**Comment by greg-1-anderson** [comment]
Robo uses a dynamic CollectionBuilder object to impersonate a task object. PHP static analysis tools might not be able to figure this out. Maybe you could just declare the return type to be TaskInterface. That's not very specific, but it should satisfy the analysis tool.

**Comment by davidsneighbour** [comment]
Yes, thanks, that works.

```
    /**
     * Create a connection object and return it.
     *
     * @param mixed[] $setup
     * @return \Robo\Contract\TaskInterface
     */
    private function getRsynchObject(array $setup): \Robo\Contract\TaskInterface
    {
        $synch = $this->taskRsync();
        $synch->recursive()
            ->excludeVcs()
            ->progress()
            ->stats()
            ->delete()
            ->exclude($this->excludePattern)
            ->checksum()
            ->rawArg('-l')
            ->wholeFile()
            ->compress()
            ->verbose();

        // remote system has a special port for ssh connections
        if (isset($setup['sshport'])) {
            $synch->rawArg("-e 'ssh -p " . $setup['sshport'] . "'");
        }

        return $synch;
    }
```

That solves the return-typehint error and opens lots of new errors about unknown methods, because TaskInterface knows only `run()`:

```
  228    Call to an undefined method Robo\Contract\TaskInterface::exec().      
  260    Call to an undefined method Robo\Contract\TaskInterface::fromPath().  
  268    Call to an undefined method Robo\Contract\TaskInterface::toPath().    
  312    Call to an undefined method Robo\Contract\TaskInterface::exec().      
```

Those errors again can be silenced by typehinting the line where the method is called to the actual task class used

```
/**
 * @var \Robo\Task\Remote\Rsync
 */
$synch = $this->getRsynchObject($setup);
```

And everyone (PHP and PhpStan) is happy.

Now, how do we hide this in the documentation? ;]
