### ISSUE TITLE
Allow IO::confirm() to take a default value

### ISSUE THREAD

**Issue by danepowell** [consolidation/Robo#849]
It would be nice to be able to easily create confirmation dialogs with a default value other than "no".

It would be trivial to accept a default argument for confirm() here, would you be open to a PR for this?
https://github.com/consolidation/Robo/blob/c2daf4e90b8cd6e896f880fac4110e7bc998a7d5/src/Common/IO.php#L131

**Comment by greg-1-anderson** [comment]
Could you use [SymfonyStyle::choice](https://github.com/symfony/symfony/blob/4.2/src/Symfony/Component/Console/Style/SymfonyStyle.php#L228) for this? I'm not clear on the use-case you're looking for, but it seems to me that if the result is not yes/no, it might be better to show the user the actual selection values.

I'm not sure why Robo is even overriding the parent method (SymfonyStyle::confirm) here; it already has a default value. Does the parent do exactly what you want?

**Comment by danepowell** [comment]
Yep the parent does what we want! I agree, not sure why Robo should override that.

**Comment by greg-1-anderson** [comment]
Would it be a backwards-compatible change to delete Robo's copy of the method?

**Comment by danepowell** [comment]
Unfortunately it would not be backwards compatible, because Symfony assumes 'true' as the default response, while Robo assumes 'false'.

**Comment by greg-1-anderson** [comment]
I guess then that it would be acceptable to copy the Symfony method up into Robo, adding the default value variable, but change the default for the default to false, if you wanted to make a PR to do that.
