### ISSUE TITLE
Prevent undefined variable warning in ImageMinify task

### ISSUE THREAD

**Issue by pixelbrackets** [consolidation/Robo#852]
### Steps to reproduce
Pass an image folder to ImageMinify task, which contains images not in the default list (png/jpg/gif/svg).

```bash
$ ls assets/images/
favicon.png
favicon.ico
```

```php
$this->taskImageMinify('assets/images/*')
    ->to('dist/images/')
    ->run();
```

### Expected behavior
Show a warning if no minifier is found for a given file extension.

### Actual behavior
Robo shows an error `Minifier method  cannot be found!`

Robo also throws a PHP warning/notification `PHP Notice:  Undefined variable: minifier in /somepath/vendor/consolidation/robo/src/Task/Assets/ImageMinify.php on line 374`

### System Configuration
Ubuntu 16.04
PHP 7.0.33

### Proposed solution

Define the missing variable at the beginning of the method.

**Comment by greg-1-anderson** [comment]
Fixed in master and 1.x. Thanks.
