### ISSUE TITLE
How to differentiate each instance of a test?

### ISSUE THREAD

**Issue by jesxs** [consolidation/Robo#860]
### Expected behavior
I'm trying to simulate multiple user logins in my web application to test how many the server can handle, so I run 5 parallel executions of the same test. My problem is that I don't know how can I tell each test to take a different username:password which for now I store in an array inside the test itself. 

I tried making it so it takes a random value each time, but obviously this isn't a reliable approach as sometimes it takes the same credentials.

I'm using chromedriver.
I'd appreciate any suggestion about this, thanks.

**Comment by greg-1-anderson** [comment]
This isn't really within the scope of features provided by Robo. However, you could do something like this:

1. Write a data file with username:passwords one per line before starting the tests
2. Protect the data file with a lock file (n.b. optional you can just read the file from the master program that launches the tests)
3. Read a username / password from the data file and then delete it
4. Set the username / password in environment variables
5. Launch the tests w/ the needed environment variables. Read env vars from tests or use default if env var not set.
