### ISSUE TITLE
Add ability to set RoboFile and RoboClass.

### ISSUE THREAD

**Issue by albertski** [consolidation/Robo#871]
My scenario is this:
I have RoboFile.php that has some methods.  I also have MyProjectRoboFile.php that has some methods.  Currently, I have to rename MyProjectRoboFile.php to RoboFile.php in order for it to run.

It would be nice if could pass RoboFile and RoboClass as an option to the robo command.

**Comment by albertski** [comment]
Before I create a pull request would this be something you guys would be okay with:

Current robo file:
```
$runner = new \Robo\Runner();
```

New robo file:
```
// Get Robo Class or Robo File set as an option.
$roboClass = NULL;
$roboFile = NULL;
foreach ($_SERVER['argv'] as $key => $argv) {
  if (substr($argv, 0, 12) == '--robo-class=') {
    $roboClass = substr($argv, 12);
    unset($_SERVER['argv'][$key]);
  }
  elseif (substr($argv, 0, 11) == '--robo-file=') {
    $roboFile = substr($argv, 11);
    unset($_SERVER['argv'][$key]);
  }
}
```

**Comment by greg-1-anderson** [comment]
Try `--load-from`

**Comment by albertski** [comment]
Oh wow. Didn't notice that. That worked great.

**Comment by greg-1-anderson** [comment]
@koppieesq ^^
