### ISSUE TITLE
Documentation is gone

### ISSUE THREAD

**Issue by digitaldonkey** [consolidation/Robo#889]
### Steps to reproduce
Go to https://robo.li/

### Expected behavior
Read Docs

### Actual behavior
404

### System Configuration
Which O.S. and PHP version are you using?

**Comment by greg-1-anderson** [comment]
Well that is odd.

https://github.com/consolidation/Robo/tree/gh-pages is intact.

**Comment by greg-1-anderson** [comment]
Clearly it's not a DNS issue either, since GitHub is apparently generating the error message.

**Comment by greg-1-anderson** [comment]
Looks like GitHub made some changes to the way GitHub pages are configured. I told GitHub to publish from robo.li, and the pages came back. The styling is different now, though, and the home page is not rendering.

**Comment by digitaldonkey** [comment]
At least it's there! But looked much much nicer before :)

`GET https://robo.li/css/robo.css net::ERR_ABORTED 404`

**Comment by greg-1-anderson** [comment]
Hm there's no robo.css in https://github.com/consolidation/Robo/tree/gh-pages/css either. I don't remember how the theme works, I'll have to look at it later to figure out why that isn't there.

**Comment by greg-1-anderson** [comment]
So it seems that mkdocs has changed too:
```
$ mkdocs build
WARNING -  Config value: 'site_favicon'. Warning: Unrecognised configuration name: site_favicon 
WARNING -  Config value: 'theme_dir'. Warning: Unrecognised configuration name: theme_dir 
WARNING -  Config value: 'pages'. Warning: The 'pages' configuration option has been deprecated and will be removed in a future release of MkDocs. Use 'nav' instead. 
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /Users/ganderson/Code/open-source/consolidation/Robo/site 
WARNING -  A relative path to 'changelog.md' is included in the 'nav' configuration, which is not found in the documentation files 
```
Perhaps what is needed is an older, pinned version of mkdocs.

**Comment by greg-1-anderson** [comment]
`theme_dir` points at robotheme, which is where `robo.css` and other important add-ins live. These are not being added, hence the default appearance and missing content.

**Comment by greg-1-anderson** [comment]
mkdocs released a 1.0 stable release with a bunch of breaking changes.

https://mkdocs.readthedocs.io/en/stable/about/release-notes/

**Comment by greg-1-anderson** [comment]
Updating to mkdocs 1.x was non-trivial. I reverted to mkdocs 0.16.3 and the site came back.

**Comment by greg-1-anderson** [comment]
On the Mac:
```
sudo pip install -Iv mkdocs==0.16.3
```
