### ISSUE TITLE
Unclear how to retrieve output with bash commands

### ISSUE THREAD

**Issue by davidsneighbour** [consolidation/Robo#901]
I am trying to retrieve the string that is echoed when I run a certain command:

```
$command = 'git branch | grep \* | cut -d \' \' -f2';
        $result = $this->taskExec($command)->run();
        if ($result->wasSuccessful()) {
            $result->provideOutputdata();
            var_dump($result->getMessage());
        }
```

There is not much documentation about this, but from what I gather from previous issues and the code itself this should var_dump the name of the current branch in my repository. It var_dumps an empty string though (not NULL). 

Is there an official way to read output from a command?

**Comment by greg-1-anderson** [comment]
For looking up info like the current branch name, you're better off avoiding taskExec.

e.g.
```
$branch = exec('git rev-parse --abbrev-ref HEAD');
```
It is not possible to get the output data from a command if using interactive mode, or if a tty is set, etc.

**Comment by davidsneighbour** [comment]
perfect, thanks. 
maybe it should be added to the documentation somewhere explicitly that taskExec can't return output?

**Comment by greg-1-anderson** [comment]
It can, but it's complicated.
