### ISSUE TITLE
Default branch here on GitHub

### ISSUE THREAD

**Issue by szepeviktor** [consolidation/Robo#908]
Please make master the default branch as PR-s should go into it.

**Comment by greg-1-anderson** [comment]
I guess I should fix the master branch so that it can be the default then.

**Comment by szepeviktor** [comment]
Thank you.

Maybe merged stale branches could also be removed https://github.com/consolidation/Robo/branches/stale

**Comment by greg-1-anderson** [comment]
In general, one should not assume that `master` is the default branch, or that `master` is the branch that PRs should go into. Sometimes, for reasons, a different branch is default.

We're back to defaulting to master on this project now, though.

**Comment by szepeviktor** [comment]
Thank you.
