### ISSUE TITLE
Phar installation link does not download 2.0

### ISSUE THREAD

**Issue by Rarst** [consolidation/Robo#918]
### Steps to reproduce

Installation instructions point to `https://robo.li/robo.phar` for download.

### Expected behavior

Download of latest stable version 2.0

### Actual behavior

Download of version 1.4.10

**Comment by Rarst** [comment]
2.0 phar also not available in respective release https://github.com/consolidation/Robo/releases/tag/2.0.0

**Comment by c33s** [comment]
@greg-1-anderson would be really cool if you add phar builds for 2.x

**Comment by greg-1-anderson** [comment]
The phar is now available at https://github.com/consolidation/Robo/releases/tag/2.0.2. It is also being correctly updated in the "robotheme" directory of the "site" branch, which is used to build the GitHub pages site that runs robo.li.

@DavertMik set up the GitHub pages site. I have not had a chance to investigate why the phar at https://robo.li/robo.phar (the target of the download button) is still downloading Robo 1.4.11. In theory, it should take whatever is pushed to the "robotheme" directory, I think.

**Comment by greg-1-anderson** [comment]
The most recent version of the robo.phar (currently 2.1.0) is up at https://robo.li/robo.phar. I believe future releases should publish to this location now as well.

**Comment by borgogelli** [comment]
@greg-1-anderson Link above is now pointing to 2.1.0 instead of 2.2.1.  The problem is not the link, but I would point out that the first version is less stable than the second one. In the 2.1.0 build there is a sort of "dependency link" bug which I have not reported because it was resolved with the last version.

**Comment by greg-1-anderson** [comment]
The phar for 2.2.1 crashes on my system, and I haven't isolated why. It complains about missing dependencies. Does build:phar work for you?

**Comment by borgogelli** [comment]
phar 2.2.0 works fine for me, and even the 2.2.1 build
but phar 2.1.0 returns the following errors:
`Fatal error: Class Robo\Tasks contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Consolidation\AnnotatedCommand\State\SavableState::currentState) in /builds/core/php-iubar-builder/vendor/consolidation/robo/src/Tasks.php on line 11`
(it looks like #824)
tested on different php projects but always on the following platform:
PHP 7.2.20 (cli) on Alpine Linux 3.10
