### ISSUE TITLE
io() from Symfony is marked deprecated

### ISSUE THREAD

**Issue by davidsneighbour** [consolidation/robo#920]
The function io() from Symfony is marked as deprecated:

```
    /**
     * Provide access to SymfonyStyle object.
     *
     * @deprecated Use a style injector instead
     *
     * @return \Symfony\Component\Console\Style\SymfonyStyle
     *
     * @see http://symfony.com/blog/new-in-symfony-2-8-console-style-guide
     */
    protected function io()
```

Should https://robo.li/getting-started/#io be removed or somehow amended for this new situation?

The documentation of Symony is not very verbose about those `style injectors`...

https://symfony.com/doc/current/console/style.html

**Comment by markdorison** [comment]
I went down the road of trying to determine the new best-practice with `io()` being marked as deprecated, but it is not yet clear to me. [Commit that added the deprecation](https://github.com/consolidation/Robo/commit/eaca05a2fa2fb98c36c61a2300b4c1b89f1e1931).

**Comment by greg-1-anderson** [comment]
I am working on a new 3.x release of Robo that clarifies the deprecation and updates the documentation to clarify what to do instead. #972 is the work-in-progress PR; the documentation updates are not done yet, but you can look at how the tests and example Robo files have changed. Note also that this PR introduces the ConsoleIO class that does not exist in any stable Robo release. ConsoleIO isa SymfonyStyle; you can simply typehint SymfonyStyle for now, although ConsoleIO will be preferred in Robo 3. Code written for Robo 2 should be compatible with Robo 3 in almost all cases; the aforementioned PR introduces just a few edge cases that break backwards compatibility.

Some further notes:

- The `io()` method is not from Symfony, it is a Robo method.
- SymfonyStyle itself is not deprecated; what is deprecated is caching SymfonyStyle, Input, Output, or any class that uses the same (e.g. Logger) in the DI container or a CommandFile.
- The preferred solution is to pass your io variables as parameters.

**Comment by davidsneighbour** [comment]
This was fixed a while back and works fine in v4 currently.

**Comment by apotek** [comment]
> I went down the road of trying to determine the new best-practice with `io()` being marked as deprecated, but it is not yet clear to me. [Commit that added the deprecation](https://github.com/consolidation/Robo/commit/eaca05a2fa2fb98c36c61a2300b4c1b89f1e1931).

Based on what I'm reading (and the code I am trying to update), I infer that in my defined commands, I can now get ConsoleIO injected into the method automagically. 

Just by changing my method from `myCommand($input1, $input2): Result {}` to `myCommand(ConsoleIO $io, $input1, $input2): Result`, I seem to successfully have the $io variable available to me. That's not clear from the docs, but it appears to be working. Once I have that $io var, if I am further passing it along to any other self-defined method/commands, I then push it as the first parameter to those commands. So `$this->myOtherCommand($param1, $param2, $param3);` becomes `$this->myOtherCommand($io, $param1, $param2, $param3);`. You can probably use named parameters as well. 

Hope this helps clarify a bit. When I looked at the docs, I could see that I could construct a new `$io = new SymfonyStyle(InputInterface, OutPutInterface);` but I wasn't sure how best to instantiate the InputInterface and OutputInterfaces. Reading https://github.com/consolidation/robo helped me see that the $io object is constructed for you, and you just need to create space for it to be injected into your methods. <-- Just my best grasp of this so far.
