### ISSUE TITLE
PHP 7.4 error "access level must be public"

### ISSUE THREAD

**Issue by danepowell** [consolidation/Robo#922]
### Steps to reproduce
Run any Acquia BLT command ("blt status") using PHP 7.4. (BLT uses the Robo framework)

### Expected behavior
Command runs without errors

### Actual behavior
> PHP Fatal error:  Access level to Robo\Common\TaskIO::printTaskInfo() must be public (as in class Robo\Common\ExecTrait) in vendor/consolidation/robo/src/Common/ProcessExecutor.php on line 63

### System Configuration
MacOS Catalina, PHP 7.4 via Homebrew

The error message is a little misleading, the problem is with Robo\Common\TaskIO::printTaskInfo(), not with ProcessExecutor. The methods there must be public to match ExecTrait. Additionally, once that's fixed, there are several other places in the codebase where this error will manifest.

**Comment by greg-1-anderson** [comment]
I just installed php 7.4 and tried running some tests. Except for a warning from Codeception, and another from Symfony Process, all of the tests passed.

I'm not sure why you'd be getting an error about printTaskInfo() needing to be public. That method is part of the ProcessExecuter by way of the TaskIO trait, which it uses. Protected access to the methods should be sufficient for the way that trait is used. No errors like that were raised by the Robo tests.

I have not tried testing Drush or Terminus with 7.4 yet, though.

**Comment by danepowell** [comment]
I confirmed that Drush doesn't have this issue. It happens most reliably when using the ProcessExecutor, as you mentioned.

I'll attach a stack trace, you can see that the error occurs as soon as ProcessExecutor.php is autoloaded.
[stacktrace.txt](https://github.com/consolidation/Robo/files/4140284/stacktrace.txt)

I agree it's a bit odd, I scoured the PHP 7.4 release notes and couldn't find anything related to trait member visibility. And yet, simply switching back to 7.3 fixes it...

**Comment by danepowell** [comment]
Now that I've had time to look through this, I think I sort of see why PHP is upset, but I'm not sure if it's a bug with PHP or Robo.

ExecTrait::printTaskInfo() is public abstract. TaskIO::printTaskInfo() is protected. ExecTrait and TaskIO are both used by ProcessExecutor.

That's like defining the same method twice in the same class, once as public abstract and once as protected. I have no idea what happens in that case, but I wonder if it would produce the same error.

I suspect what's happening is that PHP is treating TaskIO::printTaskInfo() as inheriting from ExecTrait::printTaskInfo(), in which case the [rules for inherited visibility](https://www.php.net/manual/en/language.oop5.abstract.php) apply:
> When inheriting from an abstract class, all methods marked abstract in the parent's class declaration must be defined by the child; additionally, these methods must be defined with the same (or a less restricted) visibility. For example, if the abstract method is defined as protected, the function implementation must be defined as either protected or public, but not private.

**Comment by greg-1-anderson** [comment]
Try editing ExecTrait right in your vendor directory, and make is protected rather than public, and see if that makes it work better.

**Comment by danepowell** [comment]
Yep that fixed it, I opened a PR with the changes that worked for me.
