### ISSUE TITLE
Parse error: syntax error, unexpected '<<' (T_SL) src/Runner.php on line 283

### ISSUE THREAD

**Issue by stamina84** [consolidation/Robo#929]
### Steps to reproduce
Clone 2.0.1 tag

### Expected behavior
Work as before

### Actual behavior
$ robo job:check-coding-standards
PHP Parse error:  syntax error, unexpected '<<' (T_SL) in /xxx/vendor/consolidation/robo/src/Runner.php on line 283
Parse error: syntax error, unexpected '<<' (T_SL) in /xxx/vendor/consolidation/robo/src/Runner.php on line 283

### System Configuration
linux xenial, php 7.3

The problem is here:
https://github.com/consolidation/Robo/blob/2.0.1/src/Runner.php#L283

**Comment by cedx** [comment]
Same issue here: got Robo v2.0.1 after doing a `composer update`.
Same parse error: Robo does not work anymore :cry:

**Comment by greg-1-anderson** [comment]
Bad build. Investigating and re-releasing.

**Comment by greg-1-anderson** [comment]
Please try Robo 2.0.2.

**Comment by stamina84** [comment]
`  - Installing consolidation/robo (2.0.2): Downloading (100%)`

Seems good now, script is running fine, thanks for quick fix!
