### ISSUE TITLE
[question] Drush command works in shell, but not in taskExec

### ISSUE THREAD

**Issue by hudri** [consolidation/Robo#930]
I'm creating a task to quickstart my Drupal projects using Drush. For some weird reasons the exact same command does not work when executed by `taskExec`

Does not work (RoboFile.php):
`$collection->taskExec("./vendor/bin/drush site:install --existing-config --MY_CREDENTIALS --no-interaction");`

Result ([corresponding Drush code](https://github.com/drupal/core/blob/8.8.x/includes/bootstrap.inc#L214))
```
In bootstrap.inc line 230:

  The configuration directory type 'sync' does not exist
```

I've double checked my Drupal settings, they are correct, and exactly the same command executed directly from the shell also does work as expected.

Works (bash):
`$: ./vendor/bin/drush site:install --existing-config --MY_CREDENTIALS --no-interaction`

Tried, did not work:
setting `taskExec()->dir(docroot/web)`
setting `taskExec()->dir(docroot)`
setting `drush --root`
setting `drush --uri`
setting Drupal's legacy `$config_directories`

Why does my command not work when called inside a RoboFile?

Environment:
PHP v7.3.14
Robo v1.4.10
Drupal v8.8.2 (Composer setup using `drupal/core-recommended` with core moved to `./web`)
Drush v10.2.1
Drupal settings.php: `$settings['config_sync_directory'] = '../config/sync'`

**Comment by greg-1-anderson** [comment]
Where is the RoboFile? Robo sets the cwd to the directory containing the RoboFile. That's the only difference I can think of. That's probably not it, though, as if that were the cause, then setting `--root` would work.

I guess the other possibility is that you have another vendor directory next to your RoboFile, and that vendor directory has another copy of Drush. That might explain what you are seeing. Not sure, though.

**Comment by hudri** [comment]
I think I've found my issue, it is not related to Robo. 

I was using Drupal's scaffold to append some custom default settings to `default.settings.php`, e.g. my custom `$settings['config_sync_directory'] = '../config/sync'`. When running `drush site:install` a `settings.php` was copied with all my additional settings, BUT those settings were not yet used by Drush/Drupal install.

In debugging I always made the mistake to continue from my failed RoboTask, which now had a pre-existing settings.php - that's why the same command did work from shell.
