### ISSUE TITLE
league/container 2.x is unmaintained and throws warnings on composer install

### ISSUE THREAD

**Issue by danepowell** [consolidation/Robo#935]
### Steps to reproduce
Run `composer install` on any project using any version of Robo.

### Expected behavior
No warnings.

### Actual behavior
Deprecation warning:
> Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.

This warning occurs because Robo depends on `"league/container": "^2.4.1",`, and league/container 2.x versions depend on the abandoned container-interop.

Additionally, league/container 2.x is [explicitly no longer supported](https://container.thephpleague.com/) as of over a year ago.

Robo should upgrade league/container to 3.x in order to fix this.

**Comment by adamzimmermann** [comment]
Just ran into this while trying to install `nunomaduro/phpinsights`.

```
$ composer why-not league/container:3.2.0
consolidation/robo  2.0.0-alpha3  requires  league/container (^2.2)
```
