### ISSUE TITLE
Any way to have all custom tasks/commands populated in the container in a \Robo\Tasks\ constructor.

### ISSUE THREAD

**Issue by defunctl** [consolidation/Robo#937]
### Steps to reproduce
Tried to use `$this->container` in a Task constructor. 

### Expected behavior
It would be very nice if it wasn't `NULL` and had all the commands in it already.

### Actual behavior
It's `NULL` and I have to populate it with `Robo::getContainer();` but the commands aren't yet available in it.

### System Configuration
Manjaro Linux, PHP 7.4.4

**Comment by greg-1-anderson** [comment]
Dependency injection in Robo is based on league/container inflection. It isn't possible to provide constructor injection with this model.

You could try overriding setContainer.
