### ISSUE TITLE
taskMinify ERROR: The each() function is deprecated. This message will be suppressed on further calls in phar:///{PATH}/robo/vendor/natxet/cssmin/src/CssMin.php:2222

### ISSUE THREAD

**Issue by btafoya** [consolidation/Robo#941]
### Steps to reproduce
        $this->taskMinify('assets/js/site.js')
            ->to('assets/js/site.min.js')
            ->singleLine(true)
            ->run();

### Expected behavior
The file is minified like expected with an error.

### Actual behavior
The file is minified like expected with an error, 
ERROR: The each() function is deprecated. This message will be suppressed on further calls in phar:///{PATH}/robo/vendor/natxet/cssmin/src/CssMin.php:2222
### System Configuration
Ubuntu PHP 7.3

**Comment by greg-1-anderson** [comment]
A PR to fix this would be most welcome.

**Comment by btafoya** [comment]
I have identified the issue. The version of cssmin in the robo phar file is outdated, (3.0.1, the current version is 3.0.6) and therefor the library needs to be updated. I am going to build a new phar archive and will include the results.

Taken from cssmin:
`        public static function initialise()
        {
                // Create the class index for autoloading or including
                $paths = array(dirname(__FILE__));
                while (list($i, $path) = each($paths))
                {
                        $subDirectorys = glob($path . "*", GLOB_MARK | GLOB_ONLYDIR | GLOB_NOSORT);
                        if (is_array($subDirectorys))
                        {
                                foreach ($subDirectorys as $subDirectory)
                                {
                                        $paths[] = $subDirectory;
                                }
                        }
                        $files = glob($path . "*.php", 0);
                        if (is_array($files))
                        {
                                foreach ($files as $file)
                                {
                                        $class = substr(basename($file), 0, -4);
                                        self::$classIndex[$class] = $file;
                                }
                        }
                }
                krsort(self::$classIndex);
                // Only use autoloading if spl_autoload_register() is available and no __autoload() is defined (because
                // __autoload() breaks if spl_autoload_register() is used.
                if (function_exists("spl_autoload_register") && !is_callable("__autoload"))
                {
                        spl_autoload_register(array(__CLASS__, "autoload"));
                }
                // Otherwise include all class files
                else
                {
                        foreach (self::$classIndex as $class => $file)
                        {
                                if (!class_exists($class))
                                {
                                        require_once($file);
                                }
                        }
                }
        }
`

**Comment by btafoya** [comment]
This is purely an issue with Robo version 1. Version 2 the issue has been resolved.

**Comment by greg-1-anderson** [comment]
Robo 2 is very similar to Robo 1, so I think most folks should be able to upgrade. If anyone needs dependencies updated in Robo 1 (e.g. if still on an old version of PHP), we could also accept PRs against the 1.x branch and make a new release.

**Comment by henning-klein-eo** [comment]
We also have this issue with robo 3.0.0

the easiest would be replacing the dependency
