### ISSUE TITLE
It is possible to have multiple RoboFiles?

### ISSUE THREAD

**Issue by derUli** [consolidation/Robo#944]
I have a RoboFile class in my project that has nearly 500 lines of code.
It would be better to be able to split the robo tasks to multiple files grouped by task topics.

Is there a better way than "chaining" multiple classes by class Y extends X, class Z extends Y , ..to do that?

**Comment by greg-1-anderson** [comment]
RoboFiles are intended for comparatively short scripts, e.g. a PHP version of a Makefile. If your use-case is more complicated than that, then you should use Robo as a Framework and make a stand-alone CLI tool. This will allow you to have as many classes with CLI commands as you want. See https://github.com/g1a/starter as an example.
