### ISSUE TITLE
2.0.4 Github zip has corrupted code

### ISSUE THREAD

**Issue by davereid** [consolidation/Robo#949]
### Steps to reproduce
Ran `composer require drush/drush` to an existing composer `drupal/recommended-project:9.0.x-dev`. It ends up downloading the 2.0.4 release from https://api.github.com/repos/consolidation/Robo/zipball/cf56df97fce473289ca039da0ef0f00c60148920. The file at src/Symfony/SymfonyStyleInjector looks like this:
```
<?php
<<<<<<< HEAD
=======

>>>>>>> master
namespace Robo\Symfony;
...
```

### Expected behavior
The file should contain valid PHP.

### Actual behavior
The file does not contain valid PHP.

### System Configuration
Windows 10 with WSL / Ubuntu 18.04 / PHP 7.3

**Comment by davereid** [comment]
Can we end up deleting the 2.0.4 release/tag?

**Comment by greg-1-anderson** [comment]
Already fixed. Pull 2.0.5.  I force-pushed a new 2.0.4, but it may be cached.
