### ISSUE TITLE
Required option InputOption::VALUE_REQUIRED not working as expected.

### ISSUE THREAD

**Issue by markdorison** [consolidation/Robo#963]
### Steps to reproduce
1. Create a command with a required option as shown in [ExampleCommands.php](https://github.com/consolidation/Robo/blob/bcbd8d5b849f3cc5d87e76f3257c14f6d7a21fac/examples/src/Robo/Plugin/Commands/ExampleCommands.php#L139-L145):

https://github.com/consolidation/Robo/blob/bcbd8d5b849f3cc5d87e76f3257c14f6d7a21fac/examples/src/Robo/Plugin/Commands/ExampleCommands.php#L139-L145

2. Call the command without specifying the option `foo`.

### Expected behavior
The command should fail with feedback since the option is required.

### Actual behavior
Command executes without complaining.

### System Configuration
macOS 10.15.6
PHP 7.4.8

**Comment by greg-1-anderson** [comment]
An option can never be required. The declaration you have made there stipulates that if `--foo` is used, it must have a value (`--foo=bar`).

**Comment by markdorison** [comment]
@greg-1-anderson Thanks for the clarification!
