### ISSUE TITLE
How to use output from tasks in subsequent tasks

### ISSUE THREAD

**Issue by markdorison** [consolidation/robo#974]
### Steps to reproduce
1. Task gets the filename of the recent database dump in an AWS S3 bucket using the AWS CLI.
1. Task downloads the most recent database dump.

### Expected behavior
I am expecting to be able to read the output of the command to determine the latest database dump and then use it in a second task to download that file.

```php
$result = $this->taskExec("aws s3 ls $bucket | tail -1 | awk -F ' ' '{print \$4}'")
  ->printOutput(FALSE)
  ->storeState('db-filename')
  ->run();
$dbFilename = $result->getState('db-filename');
```

### Actual behavior
I have read the [Robo's documentation on chained state](https://robo.li/collections/#chained-state) but I was unable to piece together how an example like mine would be best implemented. The closest I got was by using `storeState()` but it is unclear how I would reference that state arbitrarily in a subsequent `exec()`. Maybe what I am trying to do is possible via this method but if so, I am missing it.

In the meantime, I have implemented what I need by using the [Symfony Process component](https://symfony.com/doc/current/components/process.html) directly, but that seems less elegant than the functionality that Robo provides in other use cases.

### System Configuration
macOS 10.15.6
PHP 7.4.9

**Comment by greg-1-anderson** [comment]
Is this perhaps a simplified example of what you're trying to do? If you literally want to call the aws cli and capture the results from stdout, you would be better off using the Symfony Process API directly, or even the php native `exec`.

The general rule is, use non-Robo APIs to gather information that you need to create your tasks, then create the tasks and run them. You only need to use the state API if you need to take the result from one of your task actions and feed it in as the parameter to a follow-on task. This usually is not necessary.

If you do need the state API and are still having trouble using it, please show me your full use case and I'll try to reproduce.

**Comment by markdorison** [comment]
@greg-1-anderson Thank you for the response!

> Is this perhaps a simplified example of what you're trying to do? If you literally want to call the aws cli and capture the results from stdout, you would be better off using the Symfony Process API directly, or even the php native exec.

That is what I am doing now and it works. It just seemed strange to need to drop to a different tool like the `Process` component only because I need to retrieve the output of the command. It elicited questions from my team in code review about why I was using Robo for seemingly similar tasks but then suddenly switching to `Process`.

> The general rule is, use non-Robo APIs to gather information that you need to create your tasks, then create the tasks and run them.

Since Robo has access to, and is even storing the output, is the fact that this is not exposed publicly more due to technical considerations or philosophical ones?

**Comment by greg-1-anderson** [comment]
The example that you gave *should* work; if it does not, it is probably a bug. It probably hasn't been reported because folks tend to not use state like this.

Task collections are convenient because they allow you to write a script where you can list the operations you want to do (your task) and have a progress bar + error checking without all of the noise of "if !error", "progress->advance()" and etc.; however, this API is *less* convenient for returning results, so it makes sense to use the lower-level APIs if you are just capturing output from a tool.

Robo is a layer on top of Symfony, so you should not feel like you are using a different framework if you want to use a lower-level API directly.

**Comment by markdorison** [comment]
> The example that you gave should work; if it does not, it is probably a bug. It probably hasn't been reported because folks tend to not use state like this.

Which example are you referring to? I'll be happy to verify and create a separate bug ticket if appropriate.

> however, this API is less convenient for returning results, so it makes sense to use the lower-level APIs if you are just capturing output from a tool.
> 
> Robo is a layer on top of Symfony, so you should not feel like you are using a different framework if you want to use a lower-level API directly.

I totally hear you on this. While I like knowing that I can call `Process` directly if needed, my feedback would be that Robo is providing great value in returning clear output to the command-line automatically, providing useful defaults, and turning a multi-line Process setup/call/execution into a single line. Maybe just consider this a respectful feature request!

Thank you for your work on Robo!

**Comment by greg-1-anderson** [comment]
Your original example, `$dbFilename = $result->getState('db-filename');` should work, I would think. I have not had time to try to reproduce.

**Comment by greg-1-anderson** [comment]
Give this another try with the latest 2.x-dev

**Comment by markdorison** [comment]
@greg-1-anderson I tested with the latest 2.x-dev. `getOutputData()` seems to be returning NULL. This is what I am seeing. 

```php
    $result = $this->taskExec('echo')
      ->args(['one', 'two', 'three'])
      ->printOutput(false)
      ->run();
    $this->say('Captured output from exec >>> ' . $result->getOutputData());
```

Output:
```
 [Exec] Running echo one two three
 [Exec] Done in 0.005s
➜  Captured output from exec >>> 
```

**Comment by greg-1-anderson** [comment]
I removed a problematic annotation from the example command. Now I am getting:
```
$ ./robo try:capture-exec
 [Exec] Running echo one two three
 [Exec] Done in 0.008s
➜  Captured output from exec >>> one two three
```
Code looks the same as what you showed. Using php 7.4 on a mac, although I don't expect platform or php version should matter here.

**Comment by markdorison** [comment]
PHP 7.4.10 on macOS 10.15.6 here.

**Comment by greg-1-anderson** [comment]
If you pull the latest 2.x, do you get the same results from `./robo try:capture-exec`?

**Comment by markdorison** [comment]
> If you pull the latest 2.x, do you get the same results from `./robo try:capture-exec`?

I updated Robo to the latest on the 2.x branch (`2.x-dev`) and copied the exact [`try:capture-exec` example command](https://github.com/consolidation/Robo/blob/97c5b546e7176d78a231289058f92a5e0738d5dc/examples/src/Robo/Plugin/Commands/ExampleCommands.php#L118-L126) into the RoboFile. This is what I am seeing:

![image](https://user-images.githubusercontent.com/20355/92798085-a4889780-f380-11ea-94d5-10f56a8a33f7.png)

**Comment by greg-1-anderson** [comment]
What if you clone Robo itself as a standalone project, run composer install, and then run `./robo try:capture-exec`?

**Comment by greg-1-anderson** [comment]
Also, do you have POSIX extensions installed?
```
$ php -i | grep POSIX
POSIX support => enabled
```

**Comment by greg-1-anderson** [comment]
Oh, I see the problem. Your robo version is 2.1.1-dev; that version does not have the bug fix. Make sure you are using Robo 2.2.1 or 2.2.2-dev.

**Comment by markdorison** [comment]
Ahh. Apparently requiring `2.x-dev` with Composer was not giving me what I expected. Once I required `2.2.1`, I now see the expected output.

Now I just need to get all my site dependencies to where I can use Robo 2. Thanks @greg-1-anderson!

**Comment by greg-1-anderson** [comment]
Robo 1 is still lightly supported; I'd accept a PR with a backport e.g. if you need to support an older version of PHP.

If you don't have any dependencies keeping you from upgrading to Robo 2, though, then that's the preferred route.

**Comment by markdorison** [comment]
I am using Robo with a few Drupal 8 sites where a number of the contrib modules are not yet ported to Drupal 9. My understanding was that the [D8 Symfony dependencies](https://github.com/drupal/core/blob/b34235840cb42907fb9ebab509fe26da1e742fa6/composer.json#L24) were my [blocker from moving to Robo 2](https://github.com/consolidation/annotated-command/blob/ef6b7e662ce2d8b0af9004307bdf26350aad4df1/composer.json#L26). Am I mistaken?

**Comment by greg-1-anderson** [comment]
I know that Drush and Terminus are still on Robo 1, but I don't remember exactly what the blockers are. If you're putting Robo in a Drupal site with Drush, though, then you'll have to stick with Robo 1 for now.

**Comment by greg-1-anderson** [comment]
I hope to get Drush to the point where it can use Robo ^1 | ^2 | ^3 pretty soon -- contingent on when I am comfortable making a stable Robo 3 release.
