### ISSUE TITLE
Tar: setIgnoreList causes empty archives

### ISSUE THREAD

**Issue by Jelle-S** [consolidation/robo#978]
Our builds started failing because the archive we create & upload to our environments were empty. After a lot of debugging I found that https://github.com/consolidation/Robo/pull/964 caused the issue. 

https://github.com/consolidation/Robo/pull/964/files#diff-b826726cd9ecd307766875aaa192e6c5R58 sets the ignoreList to an empty array. Then it calls the `setIgnoreList` method on the tar object: https://github.com/consolidation/Robo/pull/964/files#diff-b826726cd9ecd307766875aaa192e6c5R209

Which causes the ignore regexp to result in `#/#` in https://github.com/pear/Archive_Tar/blob/master/Archive/Tar.php#L732

This regexp matches all our files, resulting in empty archives :(

**Comment by greg-1-anderson** [comment]
I wonder why the tests pass in this scenario? Do all tests have a non-empty ignore list now?

Please see if #979 fixes the issue for you. I'll make a quick release to fix without tests, but it would be good to have a test with an empty ignore list as a follow-on PR.

cc @obriat

**Comment by obriat** [comment]
My bad, I didn't test this (obvious) case. 
#979 seems fine
